import {test} from 'node:test'
import assert from 'node:assert/strict'
import {createProjectImageTools} from '../supabase/functions/_shared/project-image-tools.ts'
const png=()=>{const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10]);const h=new DataView(b.buffer);h.setUint32(16,1024);h.setUint32(20,1024);return b}
const args={prompt:'Instruction showing the project assembly',title:'Assembly',purpose:'instruction',target_kind:'plan_step',target_id:'step',request_quote:'Gör bilden'}
function fixture(){const calls:any[]=[];let count=0;const opts={projectId:'A',message:'Gör bilden vid steget',deadline:Date.now()+200000,hasAccess:async()=>true,writer:{remaining:8,commit:async(p:any)=>{calls.push(p);return {status:'saved',receipt:{recordId:p.record_id}}}} as any,generate:async()=>{count++;return {ok:true as const,image:png()}},upload:async(id:string,_bytes:Uint8Array)=>{calls.push({upload:id})}};return {opts,calls,get generations(){return count}}}
test('an image is ready only after reserve, upload and finalize, using the same identity',async()=>{const f=fixture();const t=createProjectImageTools(f.opts);const r=await t.execute('generate_project_image',args);assert.equal(r.saved,true);assert.deepEqual(f.calls.map(p=>p.kind??'upload'),['image_reserve','upload','image_finalize']);assert.equal(f.calls[0].record_id,f.calls[1].upload);assert.equal(f.calls[0].record_id,f.calls[2].record_id);assert.equal(f.calls[0].data.target_kind,'plan_step')})
test('interrupted upload retains recoverable identity and prevents blind duplicate generation',async()=>{const f=fixture();f.opts.upload=async()=>{throw new Error('offline')};const t=createProjectImageTools(f.opts);const r=await t.execute('generate_project_image',args);assert.equal(r.status,'partial');assert.equal(r.saved,false);assert(r.media_id);assert.equal(f.calls.length,1);assert.equal((await t.execute('generate_project_image',args)).status,'budget_exhausted');assert.equal(f.generations,1)})
test('unauthorised quote and revoked membership never generate or reserve',async()=>{const f=fixture();const t=createProjectImageTools(f.opts);assert.equal((await t.execute('generate_project_image',{...args,request_quote:'invented'})).status,'invalid');f.opts.hasAccess=async()=>false;await assert.rejects(t.execute('generate_project_image',args),/project_denied/);assert.equal(f.generations,0);assert.equal(f.calls.length,0)})
test('finalization recovery never regenerates or uploads an image',async()=>{const f=fixture();const t=createProjectImageTools(f.opts);await t.execute('finalize_project_image',{media_id:'pending',request_quote:'Gör bilden'});assert.equal(f.generations,0);assert.deepEqual(f.calls.map(p=>p.kind),['image_finalize'])})
