/** Publish the bounded correction tool and exact-version drawing input. Preserve
 * live catalog edits, roles/model prices and immutable pinned manifests. */
import {readFileSync,writeFileSync} from 'node:fs'
import {CONSTRUCTION_PARAMETER_TOOL} from '../supabase/functions/_shared/construction-draft.ts'
import {DESIGN_CAD_TOOL} from '../supabase/functions/_shared/cad-assistant.ts'

const contracts=[CONSTRUCTION_PARAMETER_TOOL.function,DESIGN_CAD_TOOL.function]
const policy=JSON.parse(readFileSync('supabase/functions/_shared/project-tools/catalog-seed.json','utf8')).find((r:any)=>r.name===CONSTRUCTION_PARAMETER_TOOL.function.name)
const sql=`-- Generated by scripts/build-ai-construction-parameter-catalog.ts.
-- Install core migration and both compatible Bob runtimes before activation.
begin;
do $construction_parameter_catalog$
declare patch jsonb; prior shared.ai_prompt_versions; template shared.ai_prompt_versions; prompt_uuid uuid; version_uuid uuid; next_version integer; definition jsonb; activation jsonb:='{}'; policy jsonb:=$parameter_policy$${JSON.stringify(policy)}$parameter_policy$::jsonb;
begin
 perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
 select v.* into template from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='tools.save_construction_draft';
 if not found then raise exception 'construction_parameter_template_missing'; end if;
 for patch in select value from jsonb_array_elements($parameter_contracts$${JSON.stringify(contracts,null,2)}$parameter_contracts$::jsonb) loop
  select v.* into prior from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='tools.'||(patch->>'name') and p.definition_kind='tool_contract';
  if not found then
   if patch->>'name'<>'change_construction_parameters' then raise exception 'construction_parameter_contract_missing'; end if;
   insert into shared.ai_prompts(app,prompt_key,label,description,content,flow,definition_kind)
    values('bob','tools.'||(patch->>'name'),policy->>'description',policy->>'description','','','tool_contract') returning id into prompt_uuid;
   prior:=template;
  else prompt_uuid:=prior.prompt_id;
  end if;
  definition:=prior.definition||patch||jsonb_build_object('handler',patch->>'name','required_parameters',patch#>'{parameters,required}','optional_parameters','[]'::jsonb,
   'additional_description',case when patch->>'name'='change_construction_parameters' then policy->>'how_to' else coalesce(prior.definition->>'additional_description','')||' For a changed construction, use change_construction_parameters, check its receipt revision and pass that exact construction_revision. Rendering cannot substitute a newer design.' end);
  select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=prompt_uuid;
  insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,metadata,content,definition,flow,available_variables)
   values(prompt_uuid,next_version,'tool_contract',1,(prior.metadata-'seed_version'-'source_revision')||jsonb_build_object('publication','construction-parameter-changes','migrated_from',case when patch->>'name'='change_construction_parameters' then 'supabase/functions/_shared/construction-draft.ts' else 'supabase/functions/_shared/cad-assistant.ts' end),prior.content,definition,prior.flow,prior.available_variables) returning id into version_uuid;
  activation:=activation||jsonb_build_object('tools.'||(patch->>'name'),version_uuid);
 end loop;
 select v.* into prior from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='bob.tools' and p.definition_kind='tool_contract' for update of p;
 if not found then raise exception 'construction_parameter_toolbox_missing'; end if;
 definition:=prior.definition;
 if not exists(select 1 from jsonb_array_elements(definition->'catalog') r where r->>'name'=policy->>'name') then
  definition:=jsonb_set(definition,'{catalog}',definition->'catalog'||jsonb_build_array(policy));
 end if;
 if not definition->'contract_keys'?('tools.'||(policy->>'name')) then
  definition:=jsonb_set(definition,'{contract_keys}',definition->'contract_keys'||jsonb_build_array('tools.'||(policy->>'name')));
 end if;
 definition:=jsonb_set(definition,'{shelves}',(select jsonb_agg(case when shelf->>'label'='Drawings and CAD' and not shelf->'tools'?(policy->>'name') then jsonb_set(shelf,'{tools}',shelf->'tools'||jsonb_build_array(policy->>'name')) else shelf end) from jsonb_array_elements(definition->'shelves') shelf));
 select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=prior.prompt_id;
 insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,metadata,content,definition,flow,available_variables)
  values(prior.prompt_id,next_version,prior.definition_kind,prior.definition_format_version,(prior.metadata-'seed_version'-'source_revision')||jsonb_build_object('publication','construction-parameter-changes'),prior.content,definition,prior.flow,prior.available_variables) returning id into version_uuid;
 activation:=activation||jsonb_build_object('bob.tools',version_uuid);
 perform shared.activate_ai_catalog('bob',activation);
end $construction_parameter_catalog$;
commit;
`
const target='supabase/migrations/20261010222920_ai_construction_parameter_catalog.sql'
if(process.argv.includes('--check')){
 if(readFileSync(target,'utf8')!==sql)throw new Error('Construction parameter catalog differs from executable tools.')
 console.log('Verified construction parameter contracts and toolbox publication.')
}else writeFileSync(target,sql)
