/** Publish only intake recovery contracts. Preserve active catalog edits and
 * immutable pinned versions; executable declarations own the wire schemas. */
import {readFileSync,readdirSync,writeFileSync} from 'node:fs'
import {INTAKE_SCHEMA} from '../supabase/functions/_shared/cad-intake.ts'
import {CAD_RESEARCH_OUTPUT_CEILING} from '../supabase/functions/_shared/cad-research.ts'

const executionRule='Historical candidate validation, renderer or model failures belong in execution_issues with their exact source refs, never in checks/additional_needs as missing measurements or unresolved design choices. They are execution work for the CAD constructor, not input prerequisites. A requested repair strategy is known when the saved requirement chooses that strategy; this does not claim that rendering has succeeded. Keep real missing physical inputs, conflicts and controlling owner choices in the existing checks/additional_needs with their existing blocking rules. Do not waive them through execution_issues. Use concise details while reporting every required check.'
export const patches=[
 {key:'tools.finish_cad_research',parameters:INTAKE_SCHEMA},
 {key:'schema.intake',schema:INTAKE_SCHEMA},
 {key:'profile.cad-research',minimum_output_tokens:CAD_RESEARCH_OUTPUT_CEILING},
 ...['cad-research.contract','cad-research.readiness-rules','cad-research.invalid-assessment'].map(key=>({key,append:executionRule})),
]
const sql=`-- Generated by scripts/build-ai-intake-recovery-catalog.ts.
-- Deploy compatible handlers first. No project data or pinned versions change.
begin;
do $cad_intake_values$
declare patch jsonb; current_version record; definition jsonb; next_content text;
  next_version integer; version_id uuid; activation jsonb := '{}';
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
  for patch in select value from jsonb_array_elements($cad_intake_recovery$${JSON.stringify(patches,null,2)}$cad_intake_recovery$::jsonb) loop
    select v.* into current_version from shared.ai_prompts p
      join shared.ai_prompt_versions v on v.id=p.active_version_id
      where p.app='bob' and p.prompt_key=patch->>'key';
    if not found then raise exception 'cad_intake_contract_missing'; end if;
    definition := current_version.definition;
    next_content := current_version.content;
    if patch ? 'parameters' then
      definition := definition || jsonb_build_object('parameters',patch->'parameters',
        'required_parameters',patch#>'{parameters,required}','optional_parameters','[]'::jsonb);
    end if;
    if patch ? 'schema' then definition := patch->'schema'; end if;
    if patch ? 'minimum_output_tokens' then
      definition := definition || jsonb_build_object('max_output_tokens',
        greatest(coalesce((definition->>'max_output_tokens')::integer,0),(patch->>'minimum_output_tokens')::integer));
    end if;
    if patch ? 'append' then next_content := next_content || E'\\n\\n' || (patch->>'append'); end if;
    select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=current_version.prompt_id;
    insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,
      metadata,content,definition,flow,available_variables)
    values(current_version.prompt_id,next_version,current_version.definition_kind,current_version.definition_format_version,
      current_version.metadata,next_content,definition,current_version.flow,current_version.available_variables)
    returning id into version_id;
    activation := activation || jsonb_build_object(patch->>'key',version_id);
  end loop;
  perform shared.activate_ai_catalog('bob',activation);
end $cad_intake_values$;
commit;
`
const at=process.argv.indexOf('--output')
const name=at>=0?process.argv[at+1]:readdirSync('supabase/migrations').filter(name=>name.endsWith('_cad_intake_execution_recovery.sql')).sort().at(-1)
if(!name)throw new Error('Provide the migration path created by Supabase CLI with --output.')
const target=name.includes('/')?name:'supabase/migrations/'+name
if(process.argv.includes('--check')){
 if(readFileSync(target,'utf8')!==sql)throw new Error('Intake recovery publication differs from executable declarations.')
 console.log('Verified intake recovery publication: '+patches.length+' definitions.')
}else{writeFileSync(target,sql);console.log('Wrote '+target)}
