/** Publish only the changed image contract; retain immutable prior manifests. */
import { readFileSync, writeFileSync } from 'node:fs'
import { IMAGE_TOOLS } from '../supabase/functions/_shared/project-image-tools.ts'

const seed = JSON.parse(readFileSync('supabase/migrations/20261009150000_seed_bob_ai_catalog.sql', 'utf8').match(/\$ai_catalog_seed\$([\s\S]+?)\$ai_catalog_seed\$/)![1])
const item = structuredClone(seed.find((row: any) => row.key === 'tools.generate_project_image'))
const tool = IMAGE_TOOLS[0].function
item.definition = { ...item.definition, ...tool, required_parameters: tool.parameters.required, optional_parameters: [],
  additional_description: 'Use exact same-project image IDs from the current chat attachments or an opened project image. Keep the photographed setting and perspective in a placement mockup. Never invent a replacement reference. Use [] when no photo should guide the illustration. A pending output is not ready; recover its existing media_id.',
  envelope: item.definition.envelope }
item.metadata = { ...item.metadata, server_fields: ['request_quote'], publication: 'chat-photo-mockups', source_revision: undefined, seed_version: undefined }
const sql = `-- Generated by scripts/build-ai-chat-image-catalog.ts from the executable image tool.
begin;
do $chat_image_catalog$
declare item jsonb; prompt_uuid uuid; version_uuid uuid; next_version integer; activation jsonb:='{}'; current_version shared.ai_prompt_versions;
begin
 perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
 for item in select value from jsonb_array_elements($ai_catalog_patch$${JSON.stringify([item], null, 2)}$ai_catalog_patch$::jsonb) loop
  select id into prompt_uuid from shared.ai_prompts where app='bob' and prompt_key=item->>'key' and definition_kind=item->>'kind' for update;
  if prompt_uuid is null then raise exception 'chat_image_catalog_definition_missing'; end if;
  select v.* into current_version from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.id=prompt_uuid;
  select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=prompt_uuid;
  insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,metadata,content,definition,flow,available_variables)
   values(prompt_uuid,next_version,item->>'kind',1,(current_version.metadata-'seed_version'-'source_revision')||item->'metadata',current_version.content,current_version.definition||item->'definition',current_version.flow,current_version.available_variables) returning id into version_uuid;
  activation:=activation||jsonb_build_object(item->>'key',version_uuid::text);
 end loop;
 -- The existing image-model row had image input disabled. Declare the verified
 -- editing capability only for Bob's current, documented GPT Image binding.
 -- Keep model choice, prices, enablement and every other model unchanged.
 update shared.ai_models m set supports_images=true
 where m.provider='openai' and m.supports_image_output
  and m.model_name in ('gpt-image-1','gpt-image-1-mini','gpt-image-1.5','gpt-image-2','gpt-image-2-2026-04-21','chatgpt-image-latest')
  and m.model_name=(select v.definition->>'model_name' from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='tier.image');
 perform shared.activate_ai_catalog('bob',activation);
end $chat_image_catalog$;
commit;
`
const output = 'supabase/migrations/20261010122005_ai_chat_image_catalog.sql'
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== sql) throw new Error('Chat image catalog differs from the executable tool.')
} else writeFileSync(output, sql)
