/** Publish only the revised CAD repair tool. Preserve live edits and pinned
 * versions; executable declarations own the provider wire contract. */
import {readFileSync,readdirSync,writeFileSync} from 'node:fs'
import {REVISE_CAD_TOOL} from '../supabase/functions/_shared/cad-revise.ts'

const patches=[{key:'tools.'+REVISE_CAD_TOOL.function.name,description:REVISE_CAD_TOOL.function.description,parameters:REVISE_CAD_TOOL.function.parameters}]
const sql=`-- Generated by scripts/build-ai-cad-revision-catalog.ts.
-- Deploy compatible handlers first. Pinned manifests stay immutable.
begin;
do $cad_revision_values$
declare patch jsonb; current_version record; definition jsonb;
  next_version integer; version_id uuid; activation jsonb := '{}';
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
  for patch in select value from jsonb_array_elements($cad_revision_contracts$${JSON.stringify(patches,null,2)}$cad_revision_contracts$::jsonb) loop
    select v.* into current_version from shared.ai_prompts p
      join shared.ai_prompt_versions v on v.id=p.active_version_id
      where p.app='bob' and p.prompt_key=patch->>'key' and p.definition_kind='tool_contract';
    if not found then raise exception 'cad_revision_contract_missing'; end if;
    definition := current_version.definition || jsonb_build_object(
      'description',patch->>'description','parameters',patch->'parameters',
      'required_parameters',patch#>'{parameters,required}','optional_parameters','[]'::jsonb);
    select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=current_version.prompt_id;
    insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,
      metadata,content,definition,flow,available_variables)
    values(current_version.prompt_id,next_version,current_version.definition_kind,current_version.definition_format_version,
      current_version.metadata,current_version.content,definition,current_version.flow,current_version.available_variables)
    returning id into version_id;
    activation := activation || jsonb_build_object(patch->>'key',version_id);
  end loop;
  perform shared.activate_ai_catalog('bob',activation);
end $cad_revision_values$;
commit;
`
const at=process.argv.indexOf('--output')
const name=at>=0?process.argv[at+1]:readdirSync('supabase/migrations').filter(name=>name.endsWith('_cad_revision_dimension_bindings.sql')).sort().at(-1)
if(!name)throw new Error('Provide the migration path with --output.')
const target=name.includes('/')?name:'supabase/migrations/'+name
if(process.argv.includes('--check')){
 if(readFileSync(target,'utf8')!==sql)throw new Error('CAD revision publication differs from executable declarations.')
 console.log('Verified CAD revision publication: '+patches.length+' contract.')
}else{writeFileSync(target,sql);console.log('Wrote '+target)}
