/** Publish only the two handoff contracts; retain active instructions, metadata,
 * policy envelopes and all unrelated database edits. Never rebuild old seeds. */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { DESIGN_CAD_TOOL } from '../supabase/functions/_shared/cad-assistant.ts'
import { PLAN_CAD_PIECES_TOOL } from '../supabase/functions/_shared/cad-pieces.ts'

const patches = [DESIGN_CAD_TOOL, PLAN_CAD_PIECES_TOOL].map(tool => ({
  key: 'tools.' + tool.function.name,
  description: tool.function.description,
  parameters: tool.function.parameters,
}))
const sql = `-- Generated by scripts/build-ai-handoff-catalog.ts from executable declarations.
-- Deploy compatible handlers before publishing. Pinned manifests stay immutable.
begin;
do $cad_handoff_values$
declare patch jsonb; current_version record; definition jsonb; metadata jsonb;
  next_version integer; version_id uuid; activation jsonb := '{}';
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
  for patch in select value from jsonb_array_elements($cad_handoff_contracts$${JSON.stringify(patches, null, 2)}$cad_handoff_contracts$::jsonb) loop
    select v.* into current_version from shared.ai_prompts p
      join shared.ai_prompt_versions v on v.id=p.active_version_id
      where p.app='bob' and p.prompt_key=patch->>'key' and p.definition_kind='tool_contract';
    if not found then raise exception 'cad_handoff_contract_missing'; end if;
    definition := current_version.definition || jsonb_build_object(
      'description',patch->>'description','parameters',patch->'parameters',
      'required_parameters',patch#>'{parameters,required}',
      'optional_parameters','[]'::jsonb);
    metadata := current_version.metadata || jsonb_build_object('server_owned_values',true,'saved_handoff_resume',true);
    select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=current_version.prompt_id;
    insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,
      metadata,content,definition,flow,available_variables)
    values(current_version.prompt_id,next_version,current_version.definition_kind,current_version.definition_format_version,
      metadata,current_version.content,definition,current_version.flow,current_version.available_variables)
    returning id into version_id;
    activation := activation || jsonb_build_object(patch->>'key',version_id);
  end loop;
  perform shared.activate_ai_catalog('bob',activation);
end $cad_handoff_values$;
commit;
`
const at = process.argv.indexOf('--output')
const name = at >= 0 ? process.argv[at + 1] : readdirSync('supabase/migrations').filter(name => name.endsWith('_cad_handoff_server_ids.sql')).sort().at(-1)
if (!name) throw new Error('Provide the migration path created by Supabase CLI with --output.')
const target = name.includes('/') ? name : 'supabase/migrations/' + name
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== sql) throw new Error('Handoff publication differs from executable declarations.')
  console.log('Verified server handoff publication: ' + patches.length + ' contracts.')
} else { writeFileSync(target, sql); console.log('Wrote ' + target) }
