-- Generated by the pinned Supabase CLI in CI; additive P1 parameter contract.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';

create function bob_private.cad_numeric_parameters(recipe jsonb)
returns table(parameter_path text,parameter_unit text,parameter_value numeric)
language plpgsql immutable security invoker set search_path='' as $$
declare d jsonb; s jsonb; row jsonb; p jsonb; k text; dims text[]; prefix text; idx integer; n integer;
begin
 if jsonb_typeof(recipe->'definitions') is distinct from 'array' or jsonb_typeof(recipe->'instances') is distinct from 'array'
  or jsonb_array_length(recipe->'definitions') not between 1 and 128 or jsonb_array_length(recipe->'instances') not between 1 and 512
  or (select count(distinct x->>'id') from jsonb_array_elements(recipe->'definitions') x)<>jsonb_array_length(recipe->'definitions')
  or (select count(distinct x->>'id') from jsonb_array_elements(recipe->'instances') x)<>jsonb_array_length(recipe->'instances') then
  raise exception 'invalid_parameter_geometry' using errcode='22023'; end if;
 for d in select value from jsonb_array_elements(recipe->'definitions') loop
  if coalesce(d->>'id','')!~'^[A-Za-z][A-Za-z0-9_.:-]{0,79}$' then raise exception 'invalid_parameter_geometry'; end if;
  n:=case when d?'cuts' then jsonb_array_length(d->'cuts') else 0 end;
  if n>16 then raise exception 'invalid_parameter_geometry'; end if;
  for idx in 0..n loop
   s:=case when idx=0 then d else d->'cuts'->(idx-1) end;
   prefix:='definitions/'||(d->>'id')||case when idx=0 then '' else '/cuts/'||(idx-1)::text end;
   dims:=case s->>'primitive' when 'box' then array['x_mm','y_mm','z_mm'] when 'cylinder' then array['diameter_mm','length_mm'] when 'tube' then array['outside_diameter_mm','wall_thickness_mm','length_mm'] end;
   if dims is null or idx>0 and s->>'primitive'='tube'
    or s-dims-(case when idx=0 then array['id','material_ref','primitive','cuts'] else array['primitive','placement'] end)<>'{}'::jsonb then raise exception 'invalid_parameter_geometry'; end if;
   foreach k in array dims loop
    if jsonb_typeof(s->k) is distinct from 'number' or (s->>k)::numeric<=0 or (s->>k)::numeric>1000000 then raise exception 'invalid_parameter_geometry'; end if;
    parameter_path:=prefix||'/'||k;parameter_unit:='mm';parameter_value:=(s->>k)::numeric;return next;
   end loop;
   if s->>'primitive'='tube' and (s->>'wall_thickness_mm')::numeric*2>=(s->>'outside_diameter_mm')::numeric then raise exception 'invalid_parameter_geometry'; end if;
   if idx>0 then
    p:=s->'placement';
    if jsonb_typeof(p) is distinct from 'object' or p-array['x','y','z','rx','ry','rz']<>'{}'::jsonb then raise exception 'invalid_parameter_geometry'; end if;
    foreach k in array array['x','y','z','rx','ry','rz'] loop
     if jsonb_typeof(p->k) is distinct from 'number' or abs((p->>k)::numeric)>(case when left(k,1)='r' then 360000 else 10000000 end) then raise exception 'invalid_parameter_geometry'; end if;
     parameter_path:=prefix||'/placement/'||k;parameter_unit:=case when left(k,1)='r' then 'deg' else 'mm' end;parameter_value:=(p->>k)::numeric;return next;
    end loop;
   end if;
  end loop;
 end loop;
 for row in select value from jsonb_array_elements(recipe->'instances') loop
  if coalesce(row->>'id','')!~'^[A-Za-z][A-Za-z0-9_.:-]{0,79}$' or not exists(select 1 from jsonb_array_elements(recipe->'definitions') x where x->>'id'=row->>'definition_id') then raise exception 'invalid_parameter_geometry'; end if;
  p:=row->'placement';
  if jsonb_typeof(p) is distinct from 'object' or p-array['x','y','z','rx','ry','rz']<>'{}'::jsonb then raise exception 'invalid_parameter_geometry'; end if;
  foreach k in array array['x','y','z','rx','ry','rz'] loop
   if jsonb_typeof(p->k) is distinct from 'number' or abs((p->>k)::numeric)>(case when left(k,1)='r' then 360000 else 10000000 end) then raise exception 'invalid_parameter_geometry'; end if;
   parameter_path:='instances/'||(row->>'id')||'/placement/'||k;parameter_unit:=case when left(k,1)='r' then 'deg' else 'mm' end;parameter_value:=(p->>k)::numeric;return next;
  end loop;
 end loop;
 for row in select value from jsonb_array_elements(coalesce(recipe->'clearances','[]')) loop
  if coalesce(row->>'id','')!~'^[A-Za-z][A-Za-z0-9_.:-]{0,79}$' or jsonb_typeof(row->'min_mm') is distinct from 'number' or (row->>'min_mm')::numeric not between 0 and 1000000 then raise exception 'invalid_parameter_geometry'; end if;
  parameter_path:='clearances/'||(row->>'id')||'/min_mm';parameter_unit:='mm';parameter_value:=(row->>'min_mm')::numeric;return next;
 end loop;
 for row in select value from jsonb_array_elements(coalesce(recipe->'motions','[]')) loop
  if coalesce(row->>'id','')!~'^[A-Za-z][A-Za-z0-9_.:-]{0,79}$' or jsonb_typeof(row->'delta') is distinct from 'object' or (row->'delta')-array['x','y','z']<>'{}'::jsonb then raise exception 'invalid_parameter_geometry'; end if;
  foreach k in array array['x','y','z'] loop
   if jsonb_typeof(row->'delta'->k) is distinct from 'number' or abs((row->'delta'->>k)::numeric)>1000000 then raise exception 'invalid_parameter_geometry'; end if;
   parameter_path:='motions/'||(row->>'id')||'/delta/'||k;parameter_unit:='mm';parameter_value:=(row->'delta'->>k)::numeric;return next;
  end loop;
 end loop;
end $$;
revoke all on function bob_private.cad_numeric_parameters(jsonb) from public,anon,authenticated,service_role;

create function bob_private.cad_image_version_matches(p_project text,p_image uuid,p_version text)
returns boolean language plpgsql stable security invoker set search_path='' as $$
declare m bob.media_assets; v jsonb; expected_links jsonb; actual_links jsonb;
begin
 select * into m from bob.media_assets where project_id=p_project and id=p_image and state='ready';
 if not found then return false; end if;
 v:=p_version::jsonb;
 if jsonb_typeof(v) is distinct from 'array' or jsonb_array_length(v)<>9 or jsonb_typeof(v->8) is distinct from 'array' then return false; end if;
 if (v->>0)::timestamptz is distinct from m.updated_at or v->>1 is distinct from m.content_type or v->2 is distinct from to_jsonb(m.byte_size)
  or v->3 is distinct from to_jsonb(m.width) or v->4 is distinct from to_jsonb(m.height) or v->>5 is distinct from m.title
  or v->>6 is distinct from m.purpose or v->>7 is distinct from coalesce(m.source_kind,'unknown') then return false; end if;
 select coalesce(jsonb_agg(item::jsonb order by item::jsonb::text),'[]') into expected_links from jsonb_array_elements_text(v->8) item;
 select coalesce(jsonb_agg(item order by item::text),'[]') into actual_links from (
  select jsonb_build_array(area_id,task_id,step_id,plan_step_id) item from bob.media_links where project_id=p_project and media_id=p_image
 ) links;
 return expected_links=actual_links;
exception when data_exception then return false;
end $$;
revoke all on function bob_private.cad_image_version_matches(text,uuid,text) from public,anon,service_role;
grant execute on function bob_private.cad_image_version_matches(text,uuid,text) to authenticated;

create function bob_private.validate_cad_parameter_graph()
returns trigger language plpgsql security invoker set search_path='' as $$
declare g jsonb:=new.manifest->'bob_parameters'; n jsonb; s jsonb; ref jsonb; b jsonb; a jsonb; c jsonb;
 checked jsonb:='{}'; paths text[]:='{}'; used text[]:='{}'; key text; u text; x numeric; y numeric; v numeric;
 m bob.measurement_revisions; sm bob.space_measurements; expected jsonb; parent jsonb; geometry jsonb;
 prior bob.artifact_cad_revisions; history boolean; target record; f jsonb; frame_ids text[]:='{}'; translation jsonb; rotation jsonb; axes jsonb; i integer; j integer; sx double precision;cx double precision;sy double precision;cy double precision;sz double precision;cz double precision;
begin
 select * into prior from bob.artifact_cad_revisions where project_id=new.project_id and artifact_id=new.artifact_id and artifact_revision=new.artifact_revision-1;
 if found and to_jsonb(prior)-'artifact_revision'=to_jsonb(new)-'artifact_revision' then
  select p.archived<>r.archived into history from bob.artifact_revisions p join bob.artifact_revisions r on r.artifact_id=p.artifact_id and r.revision=p.revision+1 where r.artifact_id=new.artifact_id and r.revision=new.artifact_revision;
  if coalesce(history,false) then return new; end if;
 end if;
 if new.source_artifact_id is not null then
  select manifest->'bob_parameters' into parent from bob.artifact_cad_revisions where project_id=new.project_id and artifact_id=new.source_artifact_id and artifact_revision=new.source_revision;
  -- Exact legacy detail views retain honest partial provenance. No reconstruction.
  if parent is null and g is null then return new; end if;
  if parent is null then raise exception 'legacy_parameters_unknown' using errcode='22023'; end if;
 end if;
 if g is null then raise exception 'cad_parameters_required' using errcode='22023'; end if;
 if jsonb_typeof(g) is distinct from 'object' or g-array['version','project_id','coverage','precision','coordinate_system','frames','nodes','bindings']<>'{}'
  or (select count(*) from jsonb_object_keys(g))<>8 or g->'version' is distinct from '1'::jsonb or g->>'project_id' is distinct from new.project_id
  or g->>'coverage' is distinct from 'complete' or g->>'precision' is distinct from 'decimal_6'
  or jsonb_typeof(g->'frames') is distinct from 'array' or jsonb_array_length(g->'frames')>16
  or jsonb_typeof(g->'nodes') is distinct from 'array' or jsonb_array_length(g->'nodes') not between 1 and 1024
  or jsonb_typeof(g->'bindings') is distinct from 'array' or jsonb_array_length(g->'bindings') not between 1 and 8192
  then raise exception 'invalid_cad_parameters' using errcode='22023'; end if;
 if g->'coordinate_system' is distinct from ('{"version":1,"length_unit":"mm","angle_unit":"deg","origin":[0,0,0],"positive_axes":[[1,0,0],[0,1,0],[0,0,1]],"rotation":"build123d_0.13_intrinsic_xyz","definition_origins":{"box":"minimum_corner","cylinder":"xy_center_z_min","tube":"xy_center_z_min"},"instance_parent":"assembly","cut_parent":"definition","frame_identity":"artifact_revision_and_recipe_path","views":{"front":{"toward_camera":[0,-1,0],"up":[0,0,1]},"right":{"toward_camera":[1,0,0],"up":[0,0,1]},"top":{"toward_camera":[0,0,1],"up":[0,1,0]},"isometric":{"toward_camera":[1,-1,1],"up":[0,0,1]}}}'::jsonb||jsonb_build_object('id',new.recipe->>'assembly_id')) then raise exception 'invalid_coordinate_system'; end if;
 if exists(select 1 from jsonb_array_elements(g->'nodes') node where node->>'role'='source' group by node->'source'->>'kind' having count(distinct node->'source'->>'id')>20)
  or exists(select 1 from jsonb_array_elements(g->'nodes') node where node->>'role'='source' group by node->'source'->>'kind',node->'source'->>'id' having count(distinct node->'source')>1) then raise exception 'parameter_source_budget_or_conflict'; end if;
 -- The earlier lineage trigger locks all canonical project measurement pins.
 -- Physical graph-only inputs additionally serialize accepted scope/head changes.
 perform 1 from bob.project_physical_scope where project_id=new.project_id order by id for share;
 perform 1 from bob.buildings where id in (select (node_item->'sources'->0->>'building_id')::uuid from jsonb_array_elements(g->'nodes') node_item where node_item->>'role'='source' and node_item->'source'->>'kind'='space_measurement') order by id for share;
 perform 1 from bob.building_spaces where id in (select (node_item->'sources'->0->>'space_id')::uuid from jsonb_array_elements(g->'nodes') node_item where node_item->>'role'='source' and node_item->'source'->>'kind'='space_measurement') order by id for share;
 perform 1 from bob.media_assets where project_id=new.project_id and id in (select substring(frame_item->>'source_ref' from 7)::uuid from jsonb_array_elements(g->'frames') frame_item where frame_item->>'kind'='image') order by id for update;
 perform 1 from bob.media_links where project_id=new.project_id and media_id in (select substring(frame_item->>'source_ref' from 7)::uuid from jsonb_array_elements(g->'frames') frame_item where frame_item->>'kind'='image') order by id for share;
 for n in select value from jsonb_array_elements(g->'nodes') loop
  key:=n->>'id';
  if coalesce(key,'')!~'^[A-Za-z][A-Za-z0-9_.:-]{0,79}$' or checked?key or jsonb_typeof(n->'normalized') is distinct from 'object'
   or (n->'normalized')-array['value','unit']<>'{}' or (select count(*) from jsonb_object_keys(n->'normalized'))<>2
   or jsonb_typeof(n->'normalized'->'value') is distinct from 'number' or jsonb_typeof(n->'sources') is distinct from 'array' then raise exception 'invalid_parameter_node'; end if;
  if n->>'role'='source' then
   if n-array['id','role','source','normalized','sources']<>'{}' or (select count(*) from jsonb_object_keys(n))<>5 or jsonb_array_length(n->'sources')<>1 then raise exception 'invalid_parameter_source'; end if;
   s:=n->'sources'->0;ref:=n->'source';u:='mm';
   if jsonb_typeof(ref) is distinct from 'object' or jsonb_typeof(ref->'id') is distinct from 'string' or coalesce(ref->>'id','')!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'invalid_parameter_source'; end if;
   if ref->>'kind'='project_measurement' then
    if ref-array['kind','id','revision']<>'{}' or jsonb_typeof(ref->'revision') is distinct from 'number' or coalesce(ref->>'revision','')!~'^[1-9][0-9]{0,8}$' then raise exception 'invalid_parameter_source'; end if;
    select r.* into m from bob.measurement_revisions r join bob.artifact_measurements pin on pin.project_id=r.project_id and pin.measurement_id=r.measurement_id and pin.measurement_revision=r.revision
     where pin.project_id=new.project_id and pin.artifact_id=new.artifact_id and pin.artifact_revision=new.artifact_revision and r.measurement_id=(ref->>'id')::uuid and r.revision=(ref->>'revision')::integer;
    if not found or m.archived or m.value is null or m.value<=0 or m.truth='unknown' then raise exception 'parameter_source_not_pinned'; end if;
    expected:=jsonb_build_object('kind','project_measurement','id',m.measurement_id,'revision',m.revision,'value',m.value::text,'unit',m.unit,'truth',m.truth,'description',m.source);
    v:=m.value*case m.unit when 'm' then 1000 when 'cm' then 10 when 'mm' then 1 end;
   elsif ref->>'kind'='space_measurement' then
    if ref-array['kind','id','space_revision']<>'{}' or jsonb_typeof(ref->'space_revision') is distinct from 'number' or coalesce(ref->>'space_revision','')!~'^[1-9][0-9]{0,8}$' then raise exception 'invalid_parameter_source'; end if;
    select r.* into sm from bob.space_measurements r join bob.project_spaces sp on sp.project_id=new.project_id and sp.id=r.space_id join bob.project_buildings bu on bu.project_id=new.project_id and bu.id=r.building_id
     where r.id=(ref->>'id')::uuid and not sp.archived and not bu.archived;
    if not found then raise exception 'physical_source_unavailable' using errcode='42501'; end if;
    if sm.space_revision<>(ref->>'space_revision')::integer or not exists(select 1 from bob.project_spaces sp where sp.project_id=new.project_id and sp.id=sm.space_id and sp.revision=sm.space_revision) then raise exception 'physical_source_changed' using errcode='40001'; end if;
    if sm.value is null or sm.value<=0 or sm.truth='unknown' then raise exception 'invalid_parameter_source'; end if;
    expected:=jsonb_build_object('kind','space_measurement','id',sm.id,'building_id',sm.building_id,'space_id',sm.space_id,'space_revision',sm.space_revision,'measurement_id',sm.measurement_id,'measurement_revision',sm.measurement_revision,'value',sm.value::text,'unit',sm.unit,'truth',sm.truth,'description',sm.source);
    v:=sm.value*case sm.unit when 'm' then 1000 when 'cm' then 10 when 'mm' then 1 end;
   else raise exception 'invalid_parameter_source'; end if;
   if s is distinct from expected or v is null then raise exception 'parameter_source_mismatch'; end if;
  elsif n->>'role' in ('decision','estimate') then
   if n-array['id','role','value','unit','reason','normalized','sources']<>'{}' or (select count(*) from jsonb_object_keys(n))<>7
    or jsonb_array_length(n->'sources')<>0 or jsonb_typeof(n->'value') is distinct from 'number' or jsonb_typeof(n->'reason') is distinct from 'string'
    or char_length(btrim(n->>'reason')) not between 1 and 2000 then raise exception 'invalid_parameter_decision'; end if;
   v:=(n->>'value')::numeric;u:=n->>'unit';
  elsif n->>'role'='derived' then
   if n-array['id','role','operation','operands','rounding','normalized','sources']<>'{}' or (select count(*) from jsonb_object_keys(n))<>7
    or jsonb_array_length(n->'sources')<>0 or jsonb_typeof(n->'operands') is distinct from 'array' or jsonb_array_length(n->'operands')<>2
    or coalesce(n->>'rounding','') not in ('exact','half_away_6') then raise exception 'invalid_parameter_formula'; end if;
   a:=checked->(n->'operands'->>0);c:=checked->(n->'operands'->>1);
   if a is null or c is null then raise exception 'parameter_cycle_or_missing_operand'; end if;
   used:=used||array[n->'operands'->>0,n->'operands'->>1];
   x:=(a->>'value')::numeric;y:=(c->>'value')::numeric;
   if n->>'operation' in ('add_v1','subtract_v1') then
    if a->>'unit'<>c->>'unit' then raise exception 'parameter_unit_mismatch'; end if;
    u:=a->>'unit';v:=case when n->>'operation'='add_v1' then x+y else x-y end;
   elsif n->>'operation'='multiply_v1' then
    if a->>'unit'<>'scalar' and c->>'unit'<>'scalar' then raise exception 'parameter_unit_mismatch'; end if;
    u:=case when a->>'unit'='scalar' then c->>'unit' else a->>'unit' end;v:=x*y;
   elsif n->>'operation'='divide_v1' then
    if y=0 or c->>'unit'<>'scalar' and a->>'unit'<>c->>'unit' then raise exception 'parameter_unit_mismatch'; end if;
    u:=case when a->>'unit'=c->>'unit' then 'scalar' else a->>'unit' end;v:=x/y;
   else raise exception 'invalid_parameter_formula'; end if;
   if n->>'rounding'='half_away_6' then v:=round(v,6); end if;
  else raise exception 'unknown_required_parameter'; end if;
  if u is null or u not in ('mm','deg','scalar') or abs(v)>1000000000 or v<>round(v,6) or n->'normalized' is distinct from jsonb_build_object('value',v,'unit',u) then raise exception 'parameter_result_mismatch'; end if;
  checked:=checked||jsonb_build_object(key,jsonb_build_object('value',v,'unit',u));
 end loop;
 for f in select value from jsonb_array_elements(g->'frames') loop
  if jsonb_typeof(f) is distinct from 'object' or f-array['id','kind','source_ref','required','reason','placement','source_version','translation_mm','rotation_degrees','axes']<>'{}'
   or (select count(*) from jsonb_object_keys(f))<>10 or coalesce(f->>'id','')!~'^[A-Za-z][A-Za-z0-9_.:-]{0,79}$' or f->>'id'=any(frame_ids)
   or jsonb_typeof(f->'required') is distinct from 'boolean' or jsonb_typeof(f->'reason') is distinct from 'string' or char_length(btrim(f->>'reason')) not between 1 and 2000 then raise exception 'invalid_coordinate_frame'; end if;
  frame_ids:=array_append(frame_ids,f->>'id');
  if f->>'kind'='room' then
   key:=substring(f->>'source_ref' from 11);
   if left(f->>'source_ref',10) is distinct from 'parameter:' or f->'source_version' is distinct from 'null'::jsonb
    or not exists(select 1 from jsonb_array_elements(g->'nodes') node_item where node_item->>'id'=key and node_item->>'role'='source' and node_item->'source'->>'kind'='space_measurement') then raise exception 'coordinate_room_source_required'; end if;
   used:=array_append(used,key);
  elsif f->>'kind'='image' then
   if coalesce(f->>'source_ref','')!~*'^image:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' or jsonb_typeof(f->'source_version') is distinct from 'string'
    or not bob_private.cad_image_version_matches(new.project_id,substring(f->>'source_ref' from 7)::uuid,f->>'source_version') then raise exception 'coordinate_image_changed' using errcode='40001'; end if;
  else raise exception 'invalid_coordinate_source'; end if;
  if f->'placement'='null'::jsonb then
   if f->'required'='true'::jsonb or f->'translation_mm' is distinct from 'null'::jsonb or f->'rotation_degrees' is distinct from 'null'::jsonb or f->'axes' is distinct from 'null'::jsonb then raise exception 'unknown_required_transform'; end if;
  else
   if jsonb_typeof(f->'placement') is distinct from 'object' or (f->'placement')-array['x','y','z','rx','ry','rz']<>'{}' or (select count(*) from jsonb_object_keys(f->'placement'))<>6 then raise exception 'invalid_coordinate_transform'; end if;
   translation:='[]';rotation:='[]';
   foreach key in array array['x','y','z','rx','ry','rz'] loop
    a:=checked->(f->'placement'->>key);u:=case when left(key,1)='r' then 'deg' else 'mm' end;
    if a is null or jsonb_typeof(f->'placement'->key) is distinct from 'string' or a->>'unit'<>u or abs((a->>'value')::numeric)>(case when u='deg' then 360000 else 10000000 end) then raise exception 'coordinate_transform_unit_or_range'; end if;
    used:=array_append(used,f->'placement'->>key);
    if u='mm' then translation:=translation||jsonb_build_array(a->'value');else rotation:=rotation||jsonb_build_array(a->'value');end if;
   end loop;
   if f->'translation_mm' is distinct from translation or f->'rotation_degrees' is distinct from rotation then raise exception 'coordinate_transform_mismatch'; end if;
   sx:=sin((rotation->>0)::double precision*pi()/180);cx:=cos((rotation->>0)::double precision*pi()/180);
   sy:=sin((rotation->>1)::double precision*pi()/180);cy:=cos((rotation->>1)::double precision*pi()/180);
   sz:=sin((rotation->>2)::double precision*pi()/180);cz:=cos((rotation->>2)::double precision*pi()/180);
   axes:=to_jsonb(array[array[cy*cz,cx*sz+sx*sy*cz,sx*sz-cx*sy*cz],array[-cy*sz,cx*cz-sx*sy*sz,sx*cz+cx*sy*sz],array[sy,-sx*cy,cx*cy]]);
   if jsonb_typeof(f->'axes') is distinct from 'array' or jsonb_array_length(f->'axes')<>3 then raise exception 'invalid_coordinate_axes'; end if;
   for i in 0..2 loop
    if jsonb_typeof(f->'axes'->i) is distinct from 'array' or jsonb_array_length(f->'axes'->i)<>3 then raise exception 'invalid_coordinate_axes'; end if;
    for j in 0..2 loop
     if jsonb_typeof(f->'axes'->i->j) is distinct from 'number' or abs((f->'axes'->i->>j)::numeric-(axes->i->>j)::numeric)>0.000000001 then raise exception 'coordinate_axes_mismatch'; end if;
    end loop;
   end loop;
  end if;
 end loop;
 select jsonb_object_agg(parameter_path,jsonb_build_object('value',parameter_value,'unit',parameter_unit)) into geometry from bob_private.cad_numeric_parameters(new.recipe);
 for b in select value from jsonb_array_elements(g->'bindings') loop
  if jsonb_typeof(b) is distinct from 'object' or b-array['path','node']<>'{}' or (select count(*) from jsonb_object_keys(b))<>2
   or jsonb_typeof(b->'path') is distinct from 'string' or jsonb_typeof(b->'node') is distinct from 'string' or b->>'path'=any(paths) or not checked?(b->>'node') then raise exception 'invalid_parameter_binding'; end if;
  paths:=array_append(paths,b->>'path');used:=array_append(used,b->>'node');
  if geometry->(b->>'path') is null or geometry->(b->>'path') is distinct from checked->(b->>'node') then raise exception 'parameter_geometry_mismatch'; end if;
 end loop;
 if exists(select 1 from jsonb_object_keys(geometry) parameter_path where not parameter_path=any(paths)) then raise exception 'unbound_required_parameter'; end if;
 if exists(select 1 from jsonb_object_keys(checked) k where not k=any(used)) then raise exception 'unused_parameter_node'; end if;
 for b in select value from jsonb_array_elements(coalesce(new.manifest->'bob_lineage'->'bindings','[]')) loop
  select node into n from jsonb_array_elements(g->'bindings') binding join jsonb_array_elements(g->'nodes') node on node->>'id'=binding->>'node'
   where binding->>'path'='definitions/'||(b->>'definition_id')||'/'||(b->>'dimension');
  if n->>'role' is distinct from 'source' or n->'sources'->0 is distinct from b->'source' then raise exception 'conflicting_parameter_bindings'; end if;
 end loop;
 if parent is not null then
  if g->'frames' is distinct from parent->'frames' or g->'coordinate_system' is distinct from parent->'coordinate_system'
   or exists(select 1 from jsonb_array_elements(g->'nodes') node where not exists(select 1 from jsonb_array_elements(parent->'nodes') old_node where old_node=node))
   or exists(select 1 from jsonb_array_elements(g->'bindings') binding where not exists(select 1 from jsonb_array_elements(parent->'bindings') old_binding where old_binding=binding)) then raise exception 'parameters_must_reuse_source'; end if;
 end if;
 return new;
end $$;
revoke all on function bob_private.validate_cad_parameter_graph() from public,anon,authenticated,service_role;
create trigger validate_cad_z_parameter_graph before insert on bob.artifact_cad_revisions for each row execute function bob_private.validate_cad_parameter_graph();

create or replace function bob.read_cad_artifact(p_project text,p_artifact uuid,p_revision integer default null)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare answer jsonb;
begin
 if not bob_private.has_project_access(p_project) then raise exception 'project_denied' using errcode='42501'; end if;
 select jsonb_build_object('artifact_id',c.artifact_id,'revision',c.artifact_revision,'recipe',c.recipe,
  'area_id',a.area_id,'component_id',c.component_id,'source_artifact_id',c.source_artifact_id,'source_revision',c.source_revision,'part_ids',c.part_ids,'step_id',c.step_id,
  'lineage',c.manifest->'bob_lineage','lineage_state',case when c.manifest?'bob_lineage' then 'partial' else 'legacy_untracked' end,
  'parameters',c.manifest->'bob_parameters','parameter_state',case when c.manifest?'bob_parameters' then 'complete' else 'legacy_partial' end)
 into answer from bob.artifact_cad_revisions c join bob.artifacts a on a.id=c.artifact_id
 where c.project_id=p_project and a.project_id=p_project and c.artifact_id=p_artifact and c.artifact_revision=coalesce(p_revision,a.current_revision);
 return answer;
end $$;
revoke all on function bob.read_cad_artifact(text,uuid,integer) from public,anon;
grant execute on function bob.read_cad_artifact(text,uuid,integer) to authenticated;

alter function bob_private.artifact_source_assessment(text,uuid,integer) rename to artifact_source_assessment_before_parameters;
create function bob_private.artifact_source_assessment(p_project text,p_artifact uuid,p_revision integer)
returns table(source_state text,source_reasons text[])
language plpgsql stable security invoker set search_path='' set join_collapse_limit=1 set from_collapse_limit=1 as $$
begin
 if not exists(select 1 from bob.artifact_cad_revisions where project_id=p_project and artifact_id=p_artifact and artifact_revision=p_revision and manifest?'bob_parameters') then
  return query select * from bob_private.artifact_source_assessment_before_parameters(p_project,p_artifact,p_revision);return;
 end if;
 return query
 with recursive own as (
  select c.*,r.target_revision,r.solution_id,r.solution_revision,r.source_media_id,a.area_id from bob.artifact_cad_revisions c
  join bob.artifact_revisions r on r.project_id=c.project_id and r.artifact_id=c.artifact_id and r.revision=c.artifact_revision
  join bob.artifacts a on a.project_id=c.project_id and a.id=c.artifact_id
  where c.project_id=p_project and c.artifact_id=p_artifact and c.artifact_revision=p_revision
 ), ancestors(id,revision,depth) as (
  select source_artifact_id,source_revision,1 from own where source_artifact_id is not null
  union all
  select c.source_artifact_id,c.source_revision,x.depth+1 from ancestors x join bob.artifact_cad_revisions c
   on c.project_id=p_project and c.artifact_id=x.id and c.artifact_revision=x.revision where c.source_artifact_id is not null and x.depth<64
 ), parent_state as (
  select coalesce(bool_or(h.id is null or r.artifact_id is null or c.artifact_id is null or target.revision is null or extra.unavailable or x.depth=64 and c.source_artifact_id is not null),false) unavailable,
   coalesce(bool_or(h.current_revision<>x.revision or current_r.archived or target.revision is distinct from r.target_revision or target.solution_id is distinct from r.solution_id or target.solution_revision is distinct from r.solution_revision or extra.changed),false) changed
  from ancestors x left join bob.artifacts h on h.project_id=p_project and h.id=x.id
   left join bob.artifact_revisions r on r.project_id=p_project and r.artifact_id=x.id and r.revision=x.revision
   left join bob.artifact_revisions current_r on current_r.project_id=p_project and current_r.artifact_id=h.id and current_r.revision=h.current_revision
   left join bob.artifact_cad_revisions c on c.project_id=p_project and c.artifact_id=x.id and c.artifact_revision=x.revision
   left join lateral(select t.* from bob.current_target t where t.project_id=p_project and (t.area_id is not distinct from h.area_id or h.area_id is not null and t.area_id is null) order by case when t.area_id is not distinct from h.area_id then 0 else 1 end limit 1) target on true
   left join lateral (
    -- Pins without graph bindings have unknown dependency scope. Preserve their
    -- conservative ancestor freshness; only explicit graph dependencies prune.
    select coalesce(bool_or(m.id is null),false) unavailable,
     coalesce(bool_or(m.revision<>pin.measurement_revision or m.archived),false) changed
    from bob.artifact_measurements pin left join bob.current_measurements m on m.project_id=pin.project_id and m.id=pin.measurement_id
    where pin.project_id=p_project and pin.artifact_id=x.id and pin.artifact_revision=x.revision
     and not exists(select 1 from jsonb_array_elements(coalesce(c.manifest->'bob_parameters'->'nodes','[]'::jsonb)) nd
      where nd->>'role'='source' and nd->'source'->>'kind'='project_measurement' and nd->'source'->>'id'=pin.measurement_id::text)
   ) extra on true
 ), project_state as (
  select coalesce(bool_or(current_m.id is null),false) unavailable,coalesce(bool_or(current_m.revision<>pin.measurement_revision or current_m.archived),false) changed
  from bob.artifact_measurements pin left join bob.current_measurements current_m on current_m.project_id=pin.project_id and current_m.id=pin.measurement_id
  where pin.project_id=p_project and pin.artifact_id=p_artifact and pin.artifact_revision=p_revision
 ), physical_pins as (
  select distinct n->'sources'->0 src from own cross join lateral jsonb_array_elements(own.manifest->'bob_parameters'->'nodes') n where n->>'role'='source' and n->'source'->>'kind'='space_measurement'
 ), physical_state as (
  select coalesce(bool_or(sm.id is null or sp.id is null or bu.id is null),false) unavailable,
   coalesce(bool_or(sp.revision is distinct from (p.src->>'space_revision')::integer or sp.archived or bu.archived),false) changed
  from physical_pins p left join bob.space_measurements sm on sm.id=(p.src->>'id')::uuid
   left join bob.project_spaces sp on sp.project_id=p_project and sp.id=(p.src->>'space_id')::uuid
   left join bob.project_buildings bu on bu.project_id=p_project and bu.id=(p.src->>'building_id')::uuid
 ), image_state as (
  select coalesce(bool_or(not bob_private.cad_image_version_matches(p_project,substring(f->>'source_ref' from 7)::uuid,f->>'source_version')),false) changed
  from own cross join lateral jsonb_array_elements(own.manifest->'bob_parameters'->'frames') f where f->>'kind'='image'
 ), conditions as (
  select target.revision is null or parent_state.unavailable or project_state.unavailable or physical_state.unavailable
   or own.source_media_id is not null and not exists(select 1 from bob.media_assets m where m.project_id=p_project and m.id=own.source_media_id and m.state='ready') unavailable,
   target.revision is distinct from own.target_revision or target.solution_id is distinct from own.solution_id or target.solution_revision is distinct from own.solution_revision target_changed,
   parent_state.changed parent_changed,project_state.changed measurement_changed,physical_state.changed physical_changed,image_state.changed image_changed
  from own cross join parent_state cross join project_state cross join physical_state cross join image_state
   left join lateral(select t.* from bob.current_target t where t.project_id=p_project and (t.area_id is not distinct from own.area_id or own.area_id is not null and t.area_id is null) order by case when t.area_id is not distinct from own.area_id then 0 else 1 end limit 1) target on true
 )
 select case when unavailable then 'unavailable' when target_changed or parent_changed or measurement_changed or physical_changed or image_changed then 'changed' else 'current' end,
  array_remove(array[case when unavailable then 'source_unavailable' end,case when target_changed then 'target_changed' end,case when parent_changed then 'drawing_source_changed' end,case when measurement_changed then 'measurements_changed' end,case when physical_changed then 'physical_source_changed' end,case when image_changed then 'image_source_changed' end],null)::text[]
 from conditions;
end $$;
revoke all on function bob_private.artifact_source_assessment(text,uuid,integer) from public,anon,service_role;
grant execute on function bob_private.artifact_source_assessment(text,uuid,integer) to authenticated;
create or replace view bob.artifact_source_status with(security_invoker=true) as
 select r.project_id,r.artifact_id,r.revision,s.source_state,s.source_reasons from bob.artifact_revisions r
 cross join lateral bob_private.artifact_source_assessment(r.project_id,r.artifact_id,r.revision) s;
commit;
