-- Generated by scripts/build-ai-cad-revision-catalog.ts.
-- Deploy compatible handlers first. Pinned manifests stay immutable.
begin;
do $cad_revision_values$
declare patch jsonb; current_version record; definition jsonb;
  next_version integer; version_id uuid; activation jsonb := '{}';
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
  for patch in select value from jsonb_array_elements($cad_revision_contracts$[
  {
    "key": "tools.revise_cad_candidate",
    "description": "Repair your last successfully rendered new geometry by sending only what changed; everything else is kept exactly. upsert replaces items with the same id (or adds them); remove deletes by id. Removing a definition, instance, array, clearance or motion also removes the bindings under its path; unreferenced decision/estimate/derived nodes are dropped. Add parameter bindings for every new or changed numeric field. dimension_bindings:null keeps the dimension source pins; an array replaces the entire list. When changing a measured dimension or swapping axes, update both dimension_bindings and the corresponding source nodes/parameter bindings together. Retain every unchanged source pin. The result is rendered, provenance-checked and reviewed exactly like render_cad_candidate and returns the full exact recipe. A rejected patch does not become the next patch base. Use render_cad_candidate only for a fresh construction.",
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "upsert",
        "remove",
        "dimension_bindings",
        "views",
        "title",
        "description",
        "assumptions"
      ],
      "properties": {
        "upsert": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "definitions",
            "instances",
            "arrays",
            "clearances",
            "motions",
            "nodes",
            "bindings"
          ],
          "properties": {
            "definitions": {
              "type": "array",
              "minItems": 0,
              "maxItems": 128,
              "items": {
                "anyOf": [
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "material_ref": {
                        "anyOf": [
                          {
                            "type": "string",
                            "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "primitive": {
                        "type": "string",
                        "enum": [
                          "box"
                        ]
                      },
                      "x_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "y_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "z_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "cuts": {
                        "type": "array",
                        "maxItems": 16,
                        "items": {
                          "anyOf": [
                            {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "placement": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "properties": {
                                    "x": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "y": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "z": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "rx": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "ry": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "rz": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    }
                                  },
                                  "required": [
                                    "x",
                                    "y",
                                    "z",
                                    "rx",
                                    "ry",
                                    "rz"
                                  ]
                                },
                                "primitive": {
                                  "type": "string",
                                  "enum": [
                                    "box"
                                  ]
                                },
                                "x_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "y_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "z_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                }
                              },
                              "required": [
                                "placement",
                                "primitive",
                                "x_mm",
                                "y_mm",
                                "z_mm"
                              ]
                            },
                            {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "placement": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "properties": {
                                    "x": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "y": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "z": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "rx": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "ry": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "rz": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    }
                                  },
                                  "required": [
                                    "x",
                                    "y",
                                    "z",
                                    "rx",
                                    "ry",
                                    "rz"
                                  ]
                                },
                                "primitive": {
                                  "type": "string",
                                  "enum": [
                                    "cylinder"
                                  ]
                                },
                                "diameter_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "length_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                }
                              },
                              "required": [
                                "placement",
                                "primitive",
                                "diameter_mm",
                                "length_mm"
                              ]
                            }
                          ]
                        }
                      }
                    },
                    "required": [
                      "id",
                      "material_ref",
                      "primitive",
                      "x_mm",
                      "y_mm",
                      "z_mm"
                    ]
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "material_ref": {
                        "anyOf": [
                          {
                            "type": "string",
                            "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "primitive": {
                        "type": "string",
                        "enum": [
                          "cylinder"
                        ]
                      },
                      "diameter_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "length_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "cuts": {
                        "type": "array",
                        "maxItems": 16,
                        "items": {
                          "anyOf": [
                            {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "placement": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "properties": {
                                    "x": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "y": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "z": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "rx": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "ry": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "rz": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    }
                                  },
                                  "required": [
                                    "x",
                                    "y",
                                    "z",
                                    "rx",
                                    "ry",
                                    "rz"
                                  ]
                                },
                                "primitive": {
                                  "type": "string",
                                  "enum": [
                                    "box"
                                  ]
                                },
                                "x_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "y_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "z_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                }
                              },
                              "required": [
                                "placement",
                                "primitive",
                                "x_mm",
                                "y_mm",
                                "z_mm"
                              ]
                            },
                            {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "placement": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "properties": {
                                    "x": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "y": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "z": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "rx": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "ry": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "rz": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    }
                                  },
                                  "required": [
                                    "x",
                                    "y",
                                    "z",
                                    "rx",
                                    "ry",
                                    "rz"
                                  ]
                                },
                                "primitive": {
                                  "type": "string",
                                  "enum": [
                                    "cylinder"
                                  ]
                                },
                                "diameter_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "length_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                }
                              },
                              "required": [
                                "placement",
                                "primitive",
                                "diameter_mm",
                                "length_mm"
                              ]
                            }
                          ]
                        }
                      }
                    },
                    "required": [
                      "id",
                      "material_ref",
                      "primitive",
                      "diameter_mm",
                      "length_mm"
                    ]
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "material_ref": {
                        "anyOf": [
                          {
                            "type": "string",
                            "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                          },
                          {
                            "type": "null"
                          }
                        ]
                      },
                      "primitive": {
                        "type": "string",
                        "enum": [
                          "tube"
                        ]
                      },
                      "outside_diameter_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "wall_thickness_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "length_mm": {
                        "type": "number",
                        "maximum": 1000000,
                        "exclusiveMinimum": 0
                      },
                      "cuts": {
                        "type": "array",
                        "maxItems": 16,
                        "items": {
                          "anyOf": [
                            {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "placement": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "properties": {
                                    "x": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "y": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "z": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "rx": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "ry": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "rz": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    }
                                  },
                                  "required": [
                                    "x",
                                    "y",
                                    "z",
                                    "rx",
                                    "ry",
                                    "rz"
                                  ]
                                },
                                "primitive": {
                                  "type": "string",
                                  "enum": [
                                    "box"
                                  ]
                                },
                                "x_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "y_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "z_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                }
                              },
                              "required": [
                                "placement",
                                "primitive",
                                "x_mm",
                                "y_mm",
                                "z_mm"
                              ]
                            },
                            {
                              "type": "object",
                              "additionalProperties": false,
                              "properties": {
                                "placement": {
                                  "type": "object",
                                  "additionalProperties": false,
                                  "properties": {
                                    "x": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "y": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "z": {
                                      "type": "number",
                                      "maximum": 10000000,
                                      "minimum": -10000000
                                    },
                                    "rx": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "ry": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    },
                                    "rz": {
                                      "type": "number",
                                      "maximum": 360000,
                                      "minimum": -360000
                                    }
                                  },
                                  "required": [
                                    "x",
                                    "y",
                                    "z",
                                    "rx",
                                    "ry",
                                    "rz"
                                  ]
                                },
                                "primitive": {
                                  "type": "string",
                                  "enum": [
                                    "cylinder"
                                  ]
                                },
                                "diameter_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                },
                                "length_mm": {
                                  "type": "number",
                                  "maximum": 1000000,
                                  "exclusiveMinimum": 0
                                }
                              },
                              "required": [
                                "placement",
                                "primitive",
                                "diameter_mm",
                                "length_mm"
                              ]
                            }
                          ]
                        }
                      }
                    },
                    "required": [
                      "id",
                      "material_ref",
                      "primitive",
                      "outside_diameter_mm",
                      "wall_thickness_mm",
                      "length_mm"
                    ]
                  }
                ]
              }
            },
            "instances": {
              "type": "array",
              "minItems": 0,
              "maxItems": 512,
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "definition_id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "placement": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "x": {
                        "type": "number",
                        "maximum": 10000000,
                        "minimum": -10000000
                      },
                      "y": {
                        "type": "number",
                        "maximum": 10000000,
                        "minimum": -10000000
                      },
                      "z": {
                        "type": "number",
                        "maximum": 10000000,
                        "minimum": -10000000
                      },
                      "rx": {
                        "type": "number",
                        "maximum": 360000,
                        "minimum": -360000
                      },
                      "ry": {
                        "type": "number",
                        "maximum": 360000,
                        "minimum": -360000
                      },
                      "rz": {
                        "type": "number",
                        "maximum": 360000,
                        "minimum": -360000
                      }
                    },
                    "required": [
                      "x",
                      "y",
                      "z",
                      "rx",
                      "ry",
                      "rz"
                    ]
                  }
                },
                "required": [
                  "id",
                  "definition_id",
                  "placement"
                ]
              }
            },
            "arrays": {
              "type": "array",
              "maxItems": 64,
              "description": "Repeat templates for evenly spaced identical parts (studs, slats, joists, rungs). Each expands to instances <id>.1..<id>.<count>. Bind arrays/<id>/start/x|y|z|rx|ry|rz (first copy) and arrays/<id>/spacing_mm (centre-to-centre step along axis); do not bind the expanded instances. Copy N sits at start + (N-1) x spacing along axis.",
              "items": {
                "type": "object",
                "additionalProperties": false,
                "required": [
                  "id",
                  "definition_id",
                  "axis",
                  "count"
                ],
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "definition_id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "axis": {
                    "type": "string",
                    "enum": [
                      "x",
                      "y",
                      "z"
                    ]
                  },
                  "count": {
                    "type": "integer",
                    "minimum": 2,
                    "maximum": 256
                  }
                }
              },
              "minItems": 0
            },
            "clearances": {
              "type": "array",
              "maxItems": 16,
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "first_id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "second_id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "min_mm": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1000000
                  }
                },
                "required": [
                  "id",
                  "first_id",
                  "second_id",
                  "min_mm"
                ]
              },
              "minItems": 0
            },
            "motions": {
              "type": "array",
              "maxItems": 16,
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "moving_ids": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 8,
                    "items": {
                      "type": "string",
                      "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                    }
                  },
                  "obstacle_ids": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 32,
                    "items": {
                      "type": "string",
                      "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                    }
                  },
                  "delta": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "x": {
                        "type": "number",
                        "maximum": 1000000,
                        "minimum": -1000000
                      },
                      "y": {
                        "type": "number",
                        "maximum": 1000000,
                        "minimum": -1000000
                      },
                      "z": {
                        "type": "number",
                        "maximum": 1000000,
                        "minimum": -1000000
                      }
                    },
                    "required": [
                      "x",
                      "y",
                      "z"
                    ]
                  }
                },
                "required": [
                  "id",
                  "moving_ids",
                  "obstacle_ids",
                  "delta"
                ]
              },
              "minItems": 0
            },
            "nodes": {
              "type": "array",
              "minItems": 0,
              "maxItems": 1024,
              "items": {
                "anyOf": [
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "role": {
                        "type": "string",
                        "enum": [
                          "source"
                        ]
                      },
                      "source": {
                        "anyOf": [
                          {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "kind": {
                                "type": "string",
                                "enum": [
                                  "project_measurement"
                                ]
                              },
                              "id": {
                                "type": "string",
                                "format": "uuid"
                              },
                              "revision": {
                                "type": "integer",
                                "minimum": 1
                              }
                            },
                            "required": [
                              "kind",
                              "id",
                              "revision"
                            ]
                          },
                          {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                              "kind": {
                                "type": "string",
                                "enum": [
                                  "space_measurement"
                                ]
                              },
                              "id": {
                                "type": "string",
                                "format": "uuid"
                              },
                              "space_revision": {
                                "type": "integer",
                                "minimum": 1
                              }
                            },
                            "required": [
                              "kind",
                              "id",
                              "space_revision"
                            ]
                          }
                        ]
                      }
                    },
                    "required": [
                      "id",
                      "role",
                      "source"
                    ]
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "role": {
                        "type": "string",
                        "enum": [
                          "decision",
                          "estimate"
                        ]
                      },
                      "value": {
                        "type": "number",
                        "minimum": -1000000000,
                        "maximum": 1000000000
                      },
                      "unit": {
                        "type": "string",
                        "enum": [
                          "mm",
                          "deg",
                          "scalar"
                        ]
                      },
                      "reason": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 2000
                      }
                    },
                    "required": [
                      "id",
                      "role",
                      "value",
                      "unit",
                      "reason"
                    ]
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "role": {
                        "type": "string",
                        "enum": [
                          "derived"
                        ]
                      },
                      "operation": {
                        "type": "string",
                        "enum": [
                          "add_v1",
                          "subtract_v1",
                          "multiply_v1",
                          "divide_v1"
                        ]
                      },
                      "operands": {
                        "type": "array",
                        "minItems": 2,
                        "maxItems": 2,
                        "items": {
                          "type": "string",
                          "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                        }
                      },
                      "rounding": {
                        "type": "string",
                        "enum": [
                          "exact",
                          "half_away_6"
                        ]
                      }
                    },
                    "required": [
                      "id",
                      "role",
                      "operation",
                      "operands",
                      "rounding"
                    ]
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "id": {
                        "type": "string",
                        "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                      },
                      "role": {
                        "type": "string",
                        "enum": [
                          "unknown"
                        ]
                      },
                      "unit": {
                        "type": "string",
                        "enum": [
                          "mm",
                          "deg",
                          "scalar"
                        ]
                      },
                      "reason": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 2000
                      }
                    },
                    "required": [
                      "id",
                      "role",
                      "unit",
                      "reason"
                    ]
                  }
                ]
              }
            },
            "bindings": {
              "type": "array",
              "minItems": 0,
              "maxItems": 8192,
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "path": {
                    "type": "string",
                    "maxLength": 240,
                    "description": "Exact slash-separated recipe path using stable IDs, e.g. definitions/side/x_mm or instances/left/placement/rz. Use no dot notation or array positions. Bind every controlling numeric field, including zero coordinates and rotations."
                  },
                  "node": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  }
                },
                "required": [
                  "path",
                  "node"
                ]
              }
            }
          }
        },
        "remove": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "definitions",
            "instances",
            "arrays",
            "clearances",
            "motions",
            "nodes",
            "bindings"
          ],
          "properties": {
            "definitions": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              }
            },
            "instances": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              }
            },
            "arrays": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              }
            },
            "clearances": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              }
            },
            "motions": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              }
            },
            "nodes": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              }
            },
            "bindings": {
              "type": "array",
              "maxItems": 256,
              "items": {
                "type": "string"
              },
              "description": "Binding paths"
            }
          }
        },
        "dimension_bindings": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "array",
              "maxItems": 32,
              "description": "Bind a part dimension to an exact project measurement OR an accepted physical space-measurement snapshot. Never copy a room snapshot into this project to fake source identity. Read physical_space_measurements and use its id and space_revision. The server supplies mm; keep original truth classes. Unbound dimensions remain design choices.",
              "items": {
                "anyOf": [
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "definition_id": {
                        "type": "string"
                      },
                      "dimension": {
                        "type": "string",
                        "enum": [
                          "x_mm",
                          "y_mm",
                          "z_mm",
                          "diameter_mm",
                          "length_mm",
                          "outside_diameter_mm",
                          "wall_thickness_mm"
                        ]
                      },
                      "measurement_id": {
                        "type": "string"
                      },
                      "revision": {
                        "type": "integer",
                        "minimum": 1
                      }
                    },
                    "required": [
                      "definition_id",
                      "dimension",
                      "measurement_id",
                      "revision"
                    ]
                  },
                  {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "definition_id": {
                        "type": "string"
                      },
                      "dimension": {
                        "type": "string",
                        "enum": [
                          "x_mm",
                          "y_mm",
                          "z_mm",
                          "diameter_mm",
                          "length_mm",
                          "outside_diameter_mm",
                          "wall_thickness_mm"
                        ]
                      },
                      "space_measurement_id": {
                        "type": "string"
                      },
                      "space_revision": {
                        "type": "integer",
                        "minimum": 1
                      }
                    },
                    "required": [
                      "definition_id",
                      "dimension",
                      "space_measurement_id",
                      "space_revision"
                    ]
                  }
                ]
              }
            }
          ]
        },
        "views": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "array",
              "minItems": 1,
              "maxItems": 4,
              "items": {
                "type": "string",
                "enum": [
                  "front",
                  "right",
                  "top",
                  "isometric"
                ]
              }
            }
          ]
        },
        "title": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 200
        },
        "description": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 6000
        },
        "assumptions": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 3500
        }
      }
    }
  }
]$cad_revision_contracts$::jsonb) loop
    select v.* into current_version from shared.ai_prompts p
      join shared.ai_prompt_versions v on v.id=p.active_version_id
      where p.app='bob' and p.prompt_key=patch->>'key' and p.definition_kind='tool_contract';
    if not found then raise exception 'cad_revision_contract_missing'; end if;
    definition := current_version.definition || jsonb_build_object(
      'description',patch->>'description','parameters',patch->'parameters',
      'required_parameters',patch#>'{parameters,required}','optional_parameters','[]'::jsonb);
    select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=current_version.prompt_id;
    insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,
      metadata,content,definition,flow,available_variables)
    values(current_version.prompt_id,next_version,current_version.definition_kind,current_version.definition_format_version,
      current_version.metadata,current_version.content,definition,current_version.flow,current_version.available_variables)
    returning id into version_id;
    activation := activation || jsonb_build_object(patch->>'key',version_id);
  end loop;
  perform shared.activate_ai_catalog('bob',activation);
end $cad_revision_values$;
commit;
