-- Generated by scripts/build-ai-chat-image-catalog.ts from the executable image tool.
begin;
do $chat_image_catalog$
declare item jsonb; prompt_uuid uuid; version_uuid uuid; next_version integer; activation jsonb:='{}'; current_version shared.ai_prompt_versions;
begin
 perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
 for item in select value from jsonb_array_elements($ai_catalog_patch$[
  {
    "key": "tools.generate_project_image",
    "kind": "tool_contract",
    "label": "Generate, save and attach a project mockup or instruction image.",
    "description": "",
    "content": "",
    "definition": {
      "name": "generate_project_image",
      "description": "Create an illustrative mockup or instruction image, save it privately and attach it where needed. For a mockup in a photographed place, copy the attached image ids into reference_image_ids and describe the planned build and what must stay unchanged (setting, perspective and existing features). These exact photos reach the image model. Use [] for an illustration without references. Read existing media to avoid duplicates; open and review the saved result before recommending it. Illustrations are not measured geometry or a fallback for failed CAD. plan_step is a living-plan Step; step is a Task instruction step.",
      "parameters": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "prompt": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "purpose": {
            "type": "string",
            "enum": [
              "proposal",
              "instruction"
            ]
          },
          "target_kind": {
            "type": "string",
            "enum": [
              "project",
              "area",
              "task",
              "step",
              "plan_step"
            ]
          },
          "target_id": {
            "type": "string"
          },
          "reference_image_ids": {
            "type": "array",
            "maxItems": 4,
            "uniqueItems": true,
            "items": {
              "type": "string",
              "format": "uuid"
            }
          },
          "request_quote": {
            "type": "string"
          }
        },
        "required": [
          "prompt",
          "title",
          "purpose",
          "target_kind",
          "target_id",
          "reference_image_ids",
          "request_quote"
        ]
      },
      "handler": "generate_project_image",
      "additional_description": "Use exact same-project image IDs from the current chat attachments or an opened project image. Keep the photographed setting and perspective in a placement mockup. Never invent a replacement reference. Use [] when no photo should guide the illustration. A pending output is not ready; recover its existing media_id.",
      "required_parameters": [
        "prompt",
        "title",
        "purpose",
        "target_kind",
        "target_id",
        "reference_image_ids",
        "request_quote"
      ],
      "optional_parameters": [],
      "envelope": {
        "type": "function",
        "schema_version": 1,
        "arguments": "JSON object validated against parameters; project binding and write provenance remain server-owned."
      },
      "expected_return": {
        "format": "json",
        "contract": "The registered handler returns its structured domain result and status; a successful write additionally returns its saved receipt. A provider tool call alone is not a saved result."
      }
    },
    "metadata": {
      "migrated_from": "supabase/functions/_shared/project-image-tools.ts",
      "label": "Generate, save and attach a project mockup or instruction image.",
      "description": "",
      "server_fields": [
        "request_quote"
      ],
      "publication": "chat-photo-mockups"
    },
    "variables": []
  }
]$ai_catalog_patch$::jsonb) loop
  select id into prompt_uuid from shared.ai_prompts where app='bob' and prompt_key=item->>'key' and definition_kind=item->>'kind' for update;
  if prompt_uuid is null then raise exception 'chat_image_catalog_definition_missing'; end if;
  select v.* into current_version from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.id=prompt_uuid;
  select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=prompt_uuid;
  insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,metadata,content,definition,flow,available_variables)
   values(prompt_uuid,next_version,item->>'kind',1,(current_version.metadata-'seed_version'-'source_revision')||item->'metadata',current_version.content,current_version.definition||item->'definition',current_version.flow,current_version.available_variables) returning id into version_uuid;
  activation:=activation||jsonb_build_object(item->>'key',version_uuid::text);
 end loop;
 -- The existing image-model row had image input disabled. Declare the verified
 -- editing capability only for Bob's current, documented GPT Image binding.
 -- Keep model choice, prices, enablement and every other model unchanged.
 update shared.ai_models m set supports_images=true
 where m.provider='openai' and m.supports_image_output
  and m.model_name in ('gpt-image-1','gpt-image-1-mini','gpt-image-1.5','gpt-image-2','gpt-image-2-2026-04-21','chatgpt-image-latest')
  and m.model_name=(select v.definition->>'model_name' from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='tier.image');
 perform shared.activate_ai_catalog('bob',activation);
end $chat_image_catalog$;
commit;
