-- Generated by scripts/build-ai-intake-recovery-catalog.ts.
-- Deploy compatible handlers first. No project data or pinned versions change.
begin;
do $cad_intake_values$
declare patch jsonb; current_version record; definition jsonb; next_content text;
  next_version integer; version_id uuid; activation jsonb := '{}';
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
  for patch in select value from jsonb_array_elements($cad_intake_recovery$[
  {
    "key": "tools.finish_cad_research",
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "checks": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string"
              },
              "status": {
                "type": "string",
                "enum": [
                  "known",
                  "assumption",
                  "missing",
                  "conflict"
                ]
              },
              "blocking": {
                "type": "boolean"
              },
              "source_refs": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "maxItems": 12
              },
              "action": {
                "type": "string",
                "enum": [
                  "none",
                  "bob_decision",
                  "measurement",
                  "owner_decision"
                ]
              },
              "detail": {
                "type": "string",
                "maxLength": 1000
              }
            },
            "required": [
              "id",
              "status",
              "blocking",
              "source_refs",
              "action",
              "detail"
            ]
          },
          "maxItems": 24
        },
        "additional_needs": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "status": {
                "type": "string",
                "enum": [
                  "known",
                  "assumption",
                  "missing",
                  "conflict"
                ]
              },
              "blocking": {
                "type": "boolean"
              },
              "source_refs": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "maxItems": 12
              },
              "action": {
                "type": "string",
                "enum": [
                  "none",
                  "bob_decision",
                  "measurement",
                  "owner_decision"
                ]
              },
              "detail": {
                "type": "string",
                "maxLength": 1000
              }
            },
            "required": [
              "status",
              "blocking",
              "source_refs",
              "action",
              "detail"
            ]
          },
          "maxItems": 20
        },
        "execution_issues": {
          "type": "array",
          "maxItems": 8,
          "description": "Historical candidate, renderer or model failures to investigate while executing CAD. These are not missing physical inputs or unresolved owner choices.",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "candidate_validation",
                  "render_service",
                  "model_service"
                ]
              },
              "detail": {
                "type": "string",
                "maxLength": 1000
              },
              "source_refs": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "minItems": 1,
                "maxItems": 12
              }
            },
            "required": [
              "kind",
              "detail",
              "source_refs"
            ]
          }
        }
      },
      "required": [
        "checks",
        "additional_needs",
        "execution_issues"
      ]
    }
  },
  {
    "key": "schema.intake",
    "schema": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "checks": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "id": {
                "type": "string"
              },
              "status": {
                "type": "string",
                "enum": [
                  "known",
                  "assumption",
                  "missing",
                  "conflict"
                ]
              },
              "blocking": {
                "type": "boolean"
              },
              "source_refs": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "maxItems": 12
              },
              "action": {
                "type": "string",
                "enum": [
                  "none",
                  "bob_decision",
                  "measurement",
                  "owner_decision"
                ]
              },
              "detail": {
                "type": "string",
                "maxLength": 1000
              }
            },
            "required": [
              "id",
              "status",
              "blocking",
              "source_refs",
              "action",
              "detail"
            ]
          },
          "maxItems": 24
        },
        "additional_needs": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "status": {
                "type": "string",
                "enum": [
                  "known",
                  "assumption",
                  "missing",
                  "conflict"
                ]
              },
              "blocking": {
                "type": "boolean"
              },
              "source_refs": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "maxItems": 12
              },
              "action": {
                "type": "string",
                "enum": [
                  "none",
                  "bob_decision",
                  "measurement",
                  "owner_decision"
                ]
              },
              "detail": {
                "type": "string",
                "maxLength": 1000
              }
            },
            "required": [
              "status",
              "blocking",
              "source_refs",
              "action",
              "detail"
            ]
          },
          "maxItems": 20
        },
        "execution_issues": {
          "type": "array",
          "maxItems": 8,
          "description": "Historical candidate, renderer or model failures to investigate while executing CAD. These are not missing physical inputs or unresolved owner choices.",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "kind": {
                "type": "string",
                "enum": [
                  "candidate_validation",
                  "render_service",
                  "model_service"
                ]
              },
              "detail": {
                "type": "string",
                "maxLength": 1000
              },
              "source_refs": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "minItems": 1,
                "maxItems": 12
              }
            },
            "required": [
              "kind",
              "detail",
              "source_refs"
            ]
          }
        }
      },
      "required": [
        "checks",
        "additional_needs",
        "execution_issues"
      ]
    }
  },
  {
    "key": "profile.cad-research",
    "minimum_output_tokens": 16000
  },
  {
    "key": "cad-research.contract",
    "append": "Historical candidate validation, renderer or model failures belong in execution_issues with their exact source refs, never in checks/additional_needs as missing measurements or unresolved design choices. They are execution work for the CAD constructor, not input prerequisites. A requested repair strategy is known when the saved requirement chooses that strategy; this does not claim that rendering has succeeded. Keep real missing physical inputs, conflicts and controlling owner choices in the existing checks/additional_needs with their existing blocking rules. Do not waive them through execution_issues. Use concise details while reporting every required check."
  },
  {
    "key": "cad-research.readiness-rules",
    "append": "Historical candidate validation, renderer or model failures belong in execution_issues with their exact source refs, never in checks/additional_needs as missing measurements or unresolved design choices. They are execution work for the CAD constructor, not input prerequisites. A requested repair strategy is known when the saved requirement chooses that strategy; this does not claim that rendering has succeeded. Keep real missing physical inputs, conflicts and controlling owner choices in the existing checks/additional_needs with their existing blocking rules. Do not waive them through execution_issues. Use concise details while reporting every required check."
  },
  {
    "key": "cad-research.invalid-assessment",
    "append": "Historical candidate validation, renderer or model failures belong in execution_issues with their exact source refs, never in checks/additional_needs as missing measurements or unresolved design choices. They are execution work for the CAD constructor, not input prerequisites. A requested repair strategy is known when the saved requirement chooses that strategy; this does not claim that rendering has succeeded. Keep real missing physical inputs, conflicts and controlling owner choices in the existing checks/additional_needs with their existing blocking rules. Do not waive them through execution_issues. Use concise details while reporting every required check."
  }
]$cad_intake_recovery$::jsonb) loop
    select v.* into current_version from shared.ai_prompts p
      join shared.ai_prompt_versions v on v.id=p.active_version_id
      where p.app='bob' and p.prompt_key=patch->>'key';
    if not found then raise exception 'cad_intake_contract_missing'; end if;
    definition := current_version.definition;
    next_content := current_version.content;
    if patch ? 'parameters' then
      definition := definition || jsonb_build_object('parameters',patch->'parameters',
        'required_parameters',patch#>'{parameters,required}','optional_parameters','[]'::jsonb);
    end if;
    if patch ? 'schema' then definition := patch->'schema'; end if;
    if patch ? 'minimum_output_tokens' then
      definition := definition || jsonb_build_object('max_output_tokens',
        greatest(coalesce((definition->>'max_output_tokens')::integer,0),(patch->>'minimum_output_tokens')::integer));
    end if;
    if patch ? 'append' then next_content := next_content || E'\n\n' || (patch->>'append'); end if;
    select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=current_version.prompt_id;
    insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,
      metadata,content,definition,flow,available_variables)
    values(current_version.prompt_id,next_version,current_version.definition_kind,current_version.definition_format_version,
      current_version.metadata,next_content,definition,current_version.flow,current_version.available_variables)
    returning id into version_id;
    activation := activation || jsonb_build_object(patch->>'key',version_id);
  end loop;
  perform shared.activate_ai_catalog('bob',activation);
end $cad_intake_values$;
commit;
