-- Generated by scripts/build-ai-construction-parameter-catalog.ts.
-- Install core migration and both compatible Bob runtimes before activation.
begin;
do $construction_parameter_catalog$
declare patch jsonb; prior shared.ai_prompt_versions; template shared.ai_prompt_versions; prompt_uuid uuid; version_uuid uuid; next_version integer; definition jsonb; activation jsonb:='{}'; policy jsonb:=$parameter_policy${"name":"change_construction_parameters","description":"Change saved construction input nodes; server recomputes dependencies and retains exact version history.","how_to":"Read the existing construction and parameter IDs. Supply only same-role/unit input changes, or an updated revision of the same source measurement. Reuse key only for exact retry. The server preserves formulas, geometry topology, materials and joints. Check the receipt revision and pass it as construction_revision to design_project_cad; no drawing is saved by this command.","schema_version":1,"always_load":false,"preload_phases":[],"active":true}$parameter_policy$::jsonb;
begin
 perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
 select v.* into template from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='tools.save_construction_draft';
 if not found then raise exception 'construction_parameter_template_missing'; end if;
 for patch in select value from jsonb_array_elements($parameter_contracts$[
  {
    "name": "change_construction_parameters",
    "description": "Change only existing input nodes in an exact saved construction. Read its stable parameter IDs first. Supply changed decision/estimate values in the SAME role/unit with an honest reason, or the newer revision of the SAME source measurement; never supply measured source values. Derived nodes, formulas, bindings, parts, materials and joints remain unchanged. The server reads the checkpoint and recomputes all dependent dimensions and placements. Unknown controlling values block saving. Use save_construction_draft for topology/material/formula changes. key identifies this intended write; exact retry reuses its receipt even after another head change. After saved, check_construction_draft at the receipt revision and pass that exact construction_revision to design_project_cad. A construction receipt alone is not a drawing delivery.",
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "key": {
          "type": "string",
          "pattern": "^[A-Za-z0-9_-]{1,80}$"
        },
        "record_id": {
          "type": "string",
          "format": "uuid"
        },
        "expected_revision": {
          "type": "integer",
          "minimum": 1,
          "maximum": 999999999
        },
        "changes": {
          "type": "array",
          "minItems": 1,
          "maxItems": 128,
          "items": {
            "anyOf": [
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "role": {
                    "type": "string",
                    "enum": [
                      "source"
                    ]
                  },
                  "source": {
                    "anyOf": [
                      {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "kind": {
                            "type": "string",
                            "enum": [
                              "project_measurement"
                            ]
                          },
                          "id": {
                            "type": "string",
                            "format": "uuid"
                          },
                          "revision": {
                            "type": "integer",
                            "minimum": 1
                          }
                        },
                        "required": [
                          "kind",
                          "id",
                          "revision"
                        ]
                      },
                      {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "kind": {
                            "type": "string",
                            "enum": [
                              "space_measurement"
                            ]
                          },
                          "id": {
                            "type": "string",
                            "format": "uuid"
                          },
                          "space_revision": {
                            "type": "integer",
                            "minimum": 1
                          }
                        },
                        "required": [
                          "kind",
                          "id",
                          "space_revision"
                        ]
                      }
                    ]
                  }
                },
                "required": [
                  "id",
                  "role",
                  "source"
                ]
              },
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "role": {
                    "type": "string",
                    "enum": [
                      "decision",
                      "estimate"
                    ]
                  },
                  "value": {
                    "type": "number",
                    "minimum": -1000000000,
                    "maximum": 1000000000
                  },
                  "unit": {
                    "type": "string",
                    "enum": [
                      "mm",
                      "deg",
                      "scalar"
                    ]
                  },
                  "reason": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000
                  }
                },
                "required": [
                  "id",
                  "role",
                  "value",
                  "unit",
                  "reason"
                ]
              },
              {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "id": {
                    "type": "string",
                    "pattern": "^[A-Za-z][A-Za-z0-9_.:-]{0,79}$"
                  },
                  "role": {
                    "type": "string",
                    "enum": [
                      "unknown"
                    ]
                  },
                  "unit": {
                    "type": "string",
                    "enum": [
                      "mm",
                      "deg",
                      "scalar"
                    ]
                  },
                  "reason": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000
                  }
                },
                "required": [
                  "id",
                  "role",
                  "unit",
                  "reason"
                ]
              }
            ]
          }
        },
        "change_note": {
          "type": "string",
          "minLength": 1,
          "maxLength": 1000
        },
        "request_quote": {
          "type": "string",
          "minLength": 1,
          "maxLength": 500
        }
      },
      "required": [
        "key",
        "record_id",
        "expected_revision",
        "changes",
        "change_note",
        "request_quote"
      ]
    }
  },
  {
    "name": "design_project_cad",
    "description": "Delegate a requested CAD drawing from the current selected Solution and its purpose-specific design intent. Resolve consequential choices through expert advice and supported selections before fixing construction geometry; reuse prior decisions and delegation. An exploratory form sketch may retain explicitly deferred choices within its stated scope. For a construction concept with parts, material revisions and typed joints, use save_construction_draft and check_construction_draft first; this drawing tool cannot replace that deliverable or repair catalog definitions. Selected original images accompany the same pinned intent for designer and reviewer. Intake returns remaining needs together; reuse existing Tasks/Steps or gather measurements in chat, then resume the same request_id. Returns a checked candidate, not a saved drawing. Specify coordinate/view directions and relevant object IDs; the assistant can fetch wider dependencies.",
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "request_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Copy the saved drawing request ID to resume after complements. Null only for a new request. With an ID, pass handoff:null and requirement_changes:[] to reuse ALL saved requirements. When the owner writes again about a request that stopped at its cost or call limit, call this immediately with that ID; the owner's new message renews the budget, which the server adds. Do not re-read requests, budgets or sources first."
        },
        "brief": {
          "type": "string"
        },
        "handoff": {
          "anyOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "deliverable": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 2000
                },
                "requirements": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 24,
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "requirement": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 2000
                      },
                      "basis": {
                        "type": "string",
                        "enum": [
                          "user_request",
                          "project_record",
                          "working_assumption"
                        ]
                      },
                      "source_ref": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "maxLength": 500
                      }
                    },
                    "required": [
                      "requirement",
                      "basis",
                      "source_ref"
                    ]
                  }
                },
                "coordinates": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "origin": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    },
                    "positive_x": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    },
                    "positive_y": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    },
                    "positive_z": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    }
                  },
                  "required": [
                    "origin",
                    "positive_x",
                    "positive_y",
                    "positive_z"
                  ]
                },
                "views": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 4,
                  "uniqueItems": true,
                  "items": {
                    "type": "string",
                    "enum": [
                      "front",
                      "right",
                      "top",
                      "isometric"
                    ]
                  }
                },
                "unresolved": {
                  "type": "array",
                  "maxItems": 20,
                  "items": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000
                  }
                }
              },
              "required": [
                "deliverable",
                "requirements",
                "coordinates",
                "views",
                "unresolved"
              ]
            },
            {
              "type": "null"
            }
          ],
          "description": "New request only: transfer owner requirements without IDs; the server creates and persists their identities. Map coordinates and views, keep unknown directions null and cite exact source refs. Resume with null: the server reads the saved handoff, including earlier corrections. Use requirement_changes only for explicit additions or changes."
        },
        "requirement_changes": {
          "type": "array",
          "maxItems": 24,
          "description": "Explicit changes to a saved request only. Empty to resume. Copy requirement_id from the saved handoff to update it; null only for a genuinely new requirement. Never invent an ID. Earlier requirements are retained.",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "requirement_id": {
                "type": [
                  "string",
                  "null"
                ],
                "maxLength": 40
              },
              "requirement": {
                "type": "string",
                "minLength": 1,
                "maxLength": 2000
              },
              "basis": {
                "type": "string",
                "enum": [
                  "user_request",
                  "project_record",
                  "working_assumption"
                ]
              },
              "source_ref": {
                "type": [
                  "string",
                  "null"
                ],
                "maxLength": 500
              }
            },
            "required": [
              "requirement_id",
              "requirement",
              "basis",
              "source_ref"
            ]
          }
        },
        "area_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "component_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "step_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Current work Step this drawing supports; read the plan and pass its exact ID when relevant. Null for a project-wide drawing. Planning is a phase."
        },
        "artifact_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Exact existing construction checkpoint to draw, or CAD Artifact to revise. A construction is freshly checked and rendered verbatim into a separate linked concept drawing; it is never redesigned here. Null only when no existing construction applies."
        },
        "construction_revision": {
          "type": [
            "integer",
            "null"
          ],
          "minimum": 1,
          "maximum": 999999999,
          "description": "For construction rendering, copy the exact revision from its saved/read receipt. The server reads and checks that version; it cannot substitute the newest design. Resume preserves the saved version. Null only for a CAD drawing without a construction source."
        }
      },
      "required": [
        "request_id",
        "brief",
        "handoff",
        "requirement_changes",
        "area_id",
        "component_id",
        "step_id",
        "artifact_id",
        "construction_revision"
      ]
    }
  }
]$parameter_contracts$::jsonb) loop
  select v.* into prior from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='tools.'||(patch->>'name') and p.definition_kind='tool_contract';
  if not found then
   if patch->>'name'<>'change_construction_parameters' then raise exception 'construction_parameter_contract_missing'; end if;
   insert into shared.ai_prompts(app,prompt_key,label,description,content,flow,definition_kind)
    values('bob','tools.'||(patch->>'name'),policy->>'description',policy->>'description','','','tool_contract') returning id into prompt_uuid;
   prior:=template;
  else prompt_uuid:=prior.prompt_id;
  end if;
  definition:=prior.definition||patch||jsonb_build_object('handler',patch->>'name','required_parameters',patch#>'{parameters,required}','optional_parameters','[]'::jsonb,
   'additional_description',case when patch->>'name'='change_construction_parameters' then policy->>'how_to' else coalesce(prior.definition->>'additional_description','')||' For a changed construction, use change_construction_parameters, check its receipt revision and pass that exact construction_revision. Rendering cannot substitute a newer design.' end);
  select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=prompt_uuid;
  insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,metadata,content,definition,flow,available_variables)
   values(prompt_uuid,next_version,'tool_contract',1,(prior.metadata-'seed_version'-'source_revision')||jsonb_build_object('publication','construction-parameter-changes','migrated_from',case when patch->>'name'='change_construction_parameters' then 'supabase/functions/_shared/construction-draft.ts' else 'supabase/functions/_shared/cad-assistant.ts' end),prior.content,definition,prior.flow,prior.available_variables) returning id into version_uuid;
  activation:=activation||jsonb_build_object('tools.'||(patch->>'name'),version_uuid);
 end loop;
 select v.* into prior from shared.ai_prompts p join shared.ai_prompt_versions v on v.id=p.active_version_id where p.app='bob' and p.prompt_key='bob.tools' and p.definition_kind='tool_contract' for update of p;
 if not found then raise exception 'construction_parameter_toolbox_missing'; end if;
 definition:=prior.definition;
 if not exists(select 1 from jsonb_array_elements(definition->'catalog') r where r->>'name'=policy->>'name') then
  definition:=jsonb_set(definition,'{catalog}',definition->'catalog'||jsonb_build_array(policy));
 end if;
 if not definition->'contract_keys'?('tools.'||(policy->>'name')) then
  definition:=jsonb_set(definition,'{contract_keys}',definition->'contract_keys'||jsonb_build_array('tools.'||(policy->>'name')));
 end if;
 definition:=jsonb_set(definition,'{shelves}',(select jsonb_agg(case when shelf->>'label'='Drawings and CAD' and not shelf->'tools'?(policy->>'name') then jsonb_set(shelf,'{tools}',shelf->'tools'||jsonb_build_array(policy->>'name')) else shelf end) from jsonb_array_elements(definition->'shelves') shelf));
 select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=prior.prompt_id;
 insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,metadata,content,definition,flow,available_variables)
  values(prior.prompt_id,next_version,prior.definition_kind,prior.definition_format_version,(prior.metadata-'seed_version'-'source_revision')||jsonb_build_object('publication','construction-parameter-changes'),prior.content,definition,prior.flow,prior.available_variables) returning id into version_uuid;
 activation:=activation||jsonb_build_object('bob.tools',version_uuid);
 perform shared.activate_ai_catalog('bob',activation);
end $construction_parameter_catalog$;
commit;
