-- BOB-UC-MATERIAL-ASSEMBLY-01 slice B: generic versioned assemblies.
-- Filename generated by the repository Supabase CLI in CI run 35696398057.
-- Source only until reviewed/applied; does not deploy the external CAD worker.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';

-- A manufactured rectangular part needs a length as well as section dimensions.
-- This is profile DATA, not an object-specific generator.
insert into bob.catalog_profiles(code,name) values('rectangular_part','Rektangulär del');
insert into bob.catalog_profile_revisions(profile_code,revision,form_code,description,published)
 values('rectangular_part',1,'rectangular_profile','Finished rectangular part with resolved or parameterised length.',false);
insert into bob.catalog_profile_fields(profile_code,profile_revision,property_key,required,min_value,max_value,position) values
 ('rectangular_part',1,'length',true,0.000001,1000000,0),
 ('rectangular_part',1,'width',true,0.000001,1000000,1),
 ('rectangular_part',1,'thickness',true,0.000001,1000000,2);
insert into bob.catalog_profile_fields(profile_code,profile_revision,property_key,required,position) values
 ('rectangular_part',1,'grade',false,20),('rectangular_part',1,'finish',false,21),('rectangular_part',1,'nominal_size',false,30);
update bob.catalog_profile_revisions set published=true where profile_code='rectangular_part' and revision=1;

create function bob_private.valid_assembly_key(p text) returns boolean
language sql immutable security invoker set search_path='' as $$
 select p is not null and length(p) between 1 and 80 and p ~ '^[A-Za-z0-9_.-]+$'
$$;

create function bob_private.valid_assembly_number(p jsonb,p_positive boolean default false,p_limit numeric default 1000000)
returns boolean language plpgsql immutable security invoker set search_path='' as $$
declare n numeric;
begin
 if jsonb_typeof(p) is distinct from 'number' then return false; end if;
 n:=(p#>>'{}')::numeric;
 return abs(n)<=p_limit and trunc(n*1000000)=n*1000000 and (not p_positive or n>0);
exception when others then return false;
end $$;

create function bob_private.valid_assembly_shape(p jsonb) returns boolean
language plpgsql immutable security invoker set search_path='' as $$
declare od numeric; wall numeric;
begin
 if p is null or jsonb_typeof(p) is distinct from 'object' or octet_length(p::text)>2000 then return false; end if;
 if p->>'kind'='box' then
   return (select count(*) from jsonb_object_keys(p))=4
     and p-array['kind','length_mm','width_mm','thickness_mm']::text[]='{}'::jsonb
     and bob_private.valid_assembly_number(p->'length_mm',true)
     and bob_private.valid_assembly_number(p->'width_mm',true)
     and bob_private.valid_assembly_number(p->'thickness_mm',true);
 elsif p->>'kind'='tube' then
   if (select count(*) from jsonb_object_keys(p))<>4
     or p-array['kind','outside_diameter_mm','wall_thickness_mm','length_mm']::text[]<>'{}'::jsonb
     or not bob_private.valid_assembly_number(p->'outside_diameter_mm',true)
     or not bob_private.valid_assembly_number(p->'wall_thickness_mm',true)
     or not bob_private.valid_assembly_number(p->'length_mm',true) then return false; end if;
   od:=(p->>'outside_diameter_mm')::numeric; wall:=(p->>'wall_thickness_mm')::numeric;
   return wall*2<od;
 end if;
 return false;
end $$;

create function bob_private.valid_assembly_views(p text[]) returns boolean
language sql immutable security invoker set search_path='' as $$
 select p is not null and cardinality(p) between 1 and 4
   and p <@ array['front','right','top','isometric']::text[]
   and cardinality(p)=(select count(distinct x) from unnest(p) x)
$$;

create function bob_private.valid_assembly_recipe(p jsonb) returns boolean
language plpgsql immutable security invoker set search_path='' as $$
declare d jsonb; i jsonb; defs text[]:='{}'; inst text[]:='{}'; views text[];
begin
 if p is null or jsonb_typeof(p)<>'object' or octet_length(p::text)>120000
   or (select count(*) from jsonb_object_keys(p))<>4
   or p-array['version','definitions','instances','views']::text[]<>'{}'::jsonb
   or p->'version' is distinct from '1'::jsonb
   or jsonb_typeof(p->'definitions')<>'array' or jsonb_array_length(p->'definitions') not between 1 and 256
   or jsonb_typeof(p->'instances')<>'array' or jsonb_array_length(p->'instances') not between 1 and 1024
   or jsonb_typeof(p->'views')<>'array' or jsonb_array_length(p->'views') not between 1 and 4 then return false; end if;
 for d in select * from jsonb_array_elements(p->'definitions') loop
   if jsonb_typeof(d)<>'object' or (select count(*) from jsonb_object_keys(d))<>4
     or d-array['key','part_id','part_revision','shape']::text[]<>'{}'::jsonb
     or not bob_private.valid_assembly_key(d->>'key')
     or coalesce(d->>'part_id','') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
     or jsonb_typeof(d->'part_revision')<>'number' or (d->>'part_revision')!~'^[1-9][0-9]{0,8}$'
     or not bob_private.valid_assembly_shape(d->'shape') or d->>'key'=any(defs) then return false; end if;
   defs:=array_append(defs,d->>'key');
 end loop;
 for i in select * from jsonb_array_elements(p->'instances') loop
   if jsonb_typeof(i)<>'object' or (select count(*) from jsonb_object_keys(i))<>4
     or i-array['key','definition_key','position_mm','rotation_deg']::text[]<>'{}'::jsonb
     or not bob_private.valid_assembly_key(i->>'key') or i->>'key'=any(inst)
     or not bob_private.valid_assembly_key(i->>'definition_key') or not (i->>'definition_key'=any(defs))
     or jsonb_typeof(i->'position_mm')<>'array' or jsonb_array_length(i->'position_mm')<>3
     or jsonb_typeof(i->'rotation_deg')<>'array' or jsonb_array_length(i->'rotation_deg')<>3
     or exists(select 1 from jsonb_array_elements(i->'position_mm') x where not bob_private.valid_assembly_number(x,false))
     or exists(select 1 from jsonb_array_elements(i->'rotation_deg') x where not bob_private.valid_assembly_number(x,false,360000)) then return false; end if;
   inst:=array_append(inst,i->>'key');
 end loop;
 select array_agg(x order by ord) into views from jsonb_array_elements_text(p->'views') with ordinality q(x,ord);
 return bob_private.valid_assembly_views(views);
exception when others then return false;
end $$;

-- Compare only dimensions that the exact catalog part actually specifies.
-- Parameter slots may be bound by the assembly; explicit unknown geometry may not.
create function bob_private.assembly_property_compatible(p_properties jsonb,p_key text,p_expected numeric)
returns boolean language plpgsql immutable security invoker set search_path='' as $$
declare v jsonb;
begin
 v:=p_properties->p_key;
 if v is null or jsonb_typeof(v)<>'object' then return false; end if;
 if v->>'parameter' is not null then return v->'value'='null'::jsonb and v->>'truth'='provided_spec' and v->>'unit'='mm'; end if;
 if v->>'truth'='unknown' or v->>'value' is null or v->>'unit'<>'mm' then return false; end if;
 return (v->>'value')::numeric=p_expected;
exception when others then return false;
end $$;

create function bob_private.assembly_part_shape_compatible(p_project text,p_part uuid,p_revision integer,p_shape jsonb)
returns boolean language plpgsql stable security invoker set search_path='' as $$
declare r bob.catalog_item_revisions; fields text[];
begin
 if not bob_private.valid_assembly_shape(p_shape) then return false; end if;
 select rev.* into r from bob.catalog_items item
 join bob.catalog_item_revisions rev on rev.item_id=item.id and rev.revision=p_revision
 where item.id=p_part and item.kind='part' and (item.project_id is null or item.project_id=p_project);
 if not found then return false; end if;
 select coalesce(array_agg(property_key),'{}') into fields from bob.catalog_profile_fields
  where profile_code=r.profile_code and profile_revision=r.profile_revision;
 if p_shape->>'kind'='box' then
   if not array['length','width','thickness']::text[] <@ fields then return false; end if;
   return bob_private.assembly_property_compatible(r.properties,'length',(p_shape->>'length_mm')::numeric)
      and bob_private.assembly_property_compatible(r.properties,'width',(p_shape->>'width_mm')::numeric)
      and bob_private.assembly_property_compatible(r.properties,'thickness',(p_shape->>'thickness_mm')::numeric);
 end if;
 if not array['outside_diameter','wall_thickness','length']::text[] <@ fields then return false; end if;
 return bob_private.assembly_property_compatible(r.properties,'outside_diameter',(p_shape->>'outside_diameter_mm')::numeric)
    and bob_private.assembly_property_compatible(r.properties,'wall_thickness',(p_shape->>'wall_thickness_mm')::numeric)
    and bob_private.assembly_property_compatible(r.properties,'length',(p_shape->>'length_mm')::numeric);
end $$;

create table bob.artifact_assemblies(
 project_id text not null references bob.projects(id) on delete cascade,
 artifact_id uuid not null,
 artifact_revision integer not null,
 contract_version integer not null check(contract_version=1),
 views text[] not null check(bob_private.valid_assembly_views(views)),
 primary key(artifact_id,artifact_revision),
 unique(artifact_id,artifact_revision,project_id),
 foreign key(artifact_id,project_id) references bob.artifacts(id,project_id) on delete cascade,
 foreign key(artifact_id,artifact_revision) references bob.artifact_revisions(artifact_id,revision) on delete cascade
);
create index artifact_assemblies_project_idx on bob.artifact_assemblies(project_id);

create table bob.artifact_assembly_definitions(
 project_id text not null,
 artifact_id uuid not null,
 artifact_revision integer not null,
 definition_key text not null check(bob_private.valid_assembly_key(definition_key)),
 part_id uuid not null,
 part_revision integer not null check(part_revision>0),
 shape jsonb not null check(bob_private.valid_assembly_shape(shape)),
 primary key(artifact_id,artifact_revision,definition_key),
 foreign key(artifact_id,artifact_revision,project_id) references bob.artifact_assemblies(artifact_id,artifact_revision,project_id) on delete cascade,
 foreign key(part_id,part_revision) references bob.catalog_item_revisions(item_id,revision)
);
create index assembly_definitions_project_idx on bob.artifact_assembly_definitions(project_id);
create index assembly_definitions_part_idx on bob.artifact_assembly_definitions(part_id,part_revision);

create table bob.artifact_assembly_instances(
 project_id text not null,
 artifact_id uuid not null,
 artifact_revision integer not null,
 instance_key text not null check(bob_private.valid_assembly_key(instance_key)),
 definition_key text not null,
 x_mm numeric not null check(abs(x_mm)<=1000000 and trunc(x_mm*1000000)=x_mm*1000000),
 y_mm numeric not null check(abs(y_mm)<=1000000 and trunc(y_mm*1000000)=y_mm*1000000),
 z_mm numeric not null check(abs(z_mm)<=1000000 and trunc(z_mm*1000000)=z_mm*1000000),
 rx_deg numeric not null check(abs(rx_deg)<=360000 and trunc(rx_deg*1000000)=rx_deg*1000000),
 ry_deg numeric not null check(abs(ry_deg)<=360000 and trunc(ry_deg*1000000)=ry_deg*1000000),
 rz_deg numeric not null check(abs(rz_deg)<=360000 and trunc(rz_deg*1000000)=rz_deg*1000000),
 primary key(artifact_id,artifact_revision,instance_key),
 foreign key(artifact_id,artifact_revision,project_id) references bob.artifact_assemblies(artifact_id,artifact_revision,project_id) on delete cascade,
 foreign key(artifact_id,artifact_revision,definition_key) references bob.artifact_assembly_definitions(artifact_id,artifact_revision,definition_key) on delete cascade
);
create index assembly_instances_project_idx on bob.artifact_assembly_instances(project_id);
create index assembly_instances_definition_idx on bob.artifact_assembly_instances(artifact_id,artifact_revision,definition_key);

alter table bob.artifact_assemblies enable row level security;
alter table bob.artifact_assembly_definitions enable row level security;
alter table bob.artifact_assembly_instances enable row level security;
revoke all on bob.artifact_assemblies,bob.artifact_assembly_definitions,bob.artifact_assembly_instances from public,anon,authenticated;
grant select on bob.artifact_assemblies,bob.artifact_assembly_definitions,bob.artifact_assembly_instances to authenticated;
create policy project_read on bob.artifact_assemblies for select to authenticated using(bob_private.has_project_access(project_id));
create policy project_read on bob.artifact_assembly_definitions for select to authenticated using(bob_private.has_project_access(project_id));
create policy project_read on bob.artifact_assembly_instances for select to authenticated using(bob_private.has_project_access(project_id));

create view bob.artifact_assembly_details with(security_invoker=true) as
select a.project_id,a.artifact_id,a.artifact_revision,a.contract_version,a.views,
 coalesce((select jsonb_agg(jsonb_build_object('key',d.definition_key,'part_id',d.part_id,'part_revision',d.part_revision,'shape',d.shape) order by d.definition_key)
   from bob.artifact_assembly_definitions d where d.artifact_id=a.artifact_id and d.artifact_revision=a.artifact_revision),'[]'::jsonb) as definitions,
 coalesce((select jsonb_agg(jsonb_build_object('key',i.instance_key,'definition_key',i.definition_key,
    'position_mm',jsonb_build_array(i.x_mm,i.y_mm,i.z_mm),'rotation_deg',jsonb_build_array(i.rx_deg,i.ry_deg,i.rz_deg)) order by i.instance_key)
   from bob.artifact_assembly_instances i where i.artifact_id=a.artifact_id and i.artifact_revision=a.artifact_revision),'[]'::jsonb) as instances,
 coalesce((select jsonb_agg(jsonb_build_object('definition_key',d.definition_key,'part_id',d.part_id,'part_revision',d.part_revision,
    'quantity',(select count(*) from bob.artifact_assembly_instances i where i.artifact_id=d.artifact_id and i.artifact_revision=d.artifact_revision and i.definition_key=d.definition_key),
    'instance_keys',coalesce((select jsonb_agg(i.instance_key order by i.instance_key) from bob.artifact_assembly_instances i where i.artifact_id=d.artifact_id and i.artifact_revision=d.artifact_revision and i.definition_key=d.definition_key),'[]'::jsonb),
    'shape',d.shape) order by d.definition_key)
   from bob.artifact_assembly_definitions d where d.artifact_id=a.artifact_id and d.artifact_revision=a.artifact_revision),'[]'::jsonb) as part_list,
 exists(select 1 from bob.artifact_assembly_definitions d join bob.catalog_items h on h.id=d.part_id
   where d.artifact_id=a.artifact_id and d.artifact_revision=a.artifact_revision and h.current_revision<>d.part_revision) as part_sources_changed
from bob.artifact_assemblies a;
revoke all on bob.artifact_assembly_details from public,anon,authenticated;
grant select on bob.artifact_assembly_details to authenticated;

create function bob_private.carry_generic_assembly() returns trigger
language plpgsql security definer set search_path='' as $$
begin
 insert into bob.artifact_assemblies(project_id,artifact_id,artifact_revision,contract_version,views)
  select p.project_id,p.artifact_id,new.revision,p.contract_version,p.views
  from bob.artifact_assemblies p where p.artifact_id=new.artifact_id and p.artifact_revision=new.revision-1;
 if found then
  insert into bob.artifact_assembly_definitions(project_id,artifact_id,artifact_revision,definition_key,part_id,part_revision,shape)
   select p.project_id,p.artifact_id,new.revision,p.definition_key,p.part_id,p.part_revision,p.shape
   from bob.artifact_assembly_definitions p where p.artifact_id=new.artifact_id and p.artifact_revision=new.revision-1;
  insert into bob.artifact_assembly_instances(project_id,artifact_id,artifact_revision,instance_key,definition_key,x_mm,y_mm,z_mm,rx_deg,ry_deg,rz_deg)
   select p.project_id,p.artifact_id,new.revision,p.instance_key,p.definition_key,p.x_mm,p.y_mm,p.z_mm,p.rx_deg,p.ry_deg,p.rz_deg
   from bob.artifact_assembly_instances p where p.artifact_id=new.artifact_id and p.artifact_revision=new.revision-1;
 end if;
 return new;
end $$;
revoke all on function bob_private.carry_generic_assembly() from public,anon,authenticated;
create trigger carry_generic_assembly after insert on bob.artifact_revisions for each row execute function bob_private.carry_generic_assembly();

create or replace function bob_private.check_single_artifact_recipe() returns trigger
language plpgsql security definer set search_path='' as $$
declare n integer;
begin
 select (exists(select 1 from bob.artifact_parametric_recipes where artifact_id=new.artifact_id and artifact_revision=new.artifact_revision))::int
 +(exists(select 1 from bob.artifact_generations where artifact_id=new.artifact_id and artifact_revision=new.artifact_revision))::int
 +(exists(select 1 from bob.artifact_room_layouts where artifact_id=new.artifact_id and artifact_revision=new.artifact_revision))::int
 +(exists(select 1 from bob.artifact_multifloor_plans where artifact_id=new.artifact_id and artifact_revision=new.artifact_revision))::int
 +(exists(select 1 from bob.artifact_stair_studies where artifact_id=new.artifact_id and artifact_revision=new.artifact_revision))::int
 +(exists(select 1 from bob.artifact_assemblies where artifact_id=new.artifact_id and artifact_revision=new.artifact_revision))::int into n;
 if n>1 then raise exception 'A drawing revision cannot have two geometry recipes';end if;
 return null;
end $$;
create constraint trigger generic_assembly_exclusive after insert or update on bob.artifact_assemblies
 deferrable initially deferred for each row execute function bob_private.check_single_artifact_recipe();

create function bob_private.artifact_assembly_command(p_project text,p_action text,p_artifact uuid,p_expected integer,p_data jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare recipe jsonb; d jsonb; i jsonb; body jsonb; saved jsonb; revision integer; views text[];
begin
 if auth.uid() is null or not bob_private.has_project_access(p_project) then raise exception 'project_denied' using errcode='42501';end if;
 if p_action is null or p_action<>all(array['create','revise']) or p_artifact is null or p_expected is null
   or p_data is null or jsonb_typeof(p_data)<>'object' or octet_length(p_data::text)>140000 then raise exception 'invalid_assembly' using errcode='22023';end if;
 if p_data-(array['title','description','assumptions','target_revision','recipe','measurements']||
    case when p_action='create' then array['area_id'] else array['change_note'] end)<>'{}'::jsonb
   or (select count(*) from jsonb_object_keys(p_data))<>7 or not bob_private.valid_assembly_recipe(p_data->'recipe')
   or jsonb_typeof(p_data->'title')<>'string' or length(btrim(p_data->>'title')) not between 1 and 200
   or jsonb_typeof(p_data->'description')<>'string' or length(btrim(p_data->>'description')) not between 1 and 6000
   or jsonb_typeof(p_data->'assumptions')<>'string' or length(p_data->>'assumptions')>3500 then raise exception 'invalid_assembly' using errcode='22023';end if;
 recipe:=p_data->'recipe';
 perform 1 from bob.projects where id=p_project for no key update;
 for d in select * from jsonb_array_elements(recipe->'definitions') order by value->>'part_id',value->>'part_revision' loop
   perform 1 from bob.catalog_items h join bob.catalog_item_revisions r on r.item_id=h.id and r.revision=(d->>'part_revision')::integer
    where h.id=(d->>'part_id')::uuid and h.kind='part' and (h.project_id is null or h.project_id=p_project) for share of h,r;
   if not found then raise exception 'catalog_part_unavailable' using errcode='42501';end if;
   if not bob_private.assembly_part_shape_compatible(p_project,(d->>'part_id')::uuid,(d->>'part_revision')::integer,d->'shape') then
     raise exception 'assembly_part_geometry_mismatch:%',d->>'key' using errcode='22023';end if;
 end loop;
 body:=jsonb_build_object('title',p_data->'title','description',p_data->'description','assumptions',p_data->'assumptions',
   'kind','detail','status','concept','source_media_id',null,'target_revision',p_data->'target_revision','measurements',p_data->'measurements');
 body:=body||case when p_action='create' then jsonb_build_object('area_id',p_data->'area_id') else jsonb_build_object('change_note',p_data->'change_note') end;
 saved:=bob_private.artifact_command(p_project,p_action,p_artifact,p_expected,body);
 revision:=(saved->>'revision')::integer;
 delete from bob.artifact_assemblies where artifact_id=p_artifact and artifact_revision=revision;
 select array_agg(x order by ord) into views from jsonb_array_elements_text(recipe->'views') with ordinality q(x,ord);
 insert into bob.artifact_assemblies(project_id,artifact_id,artifact_revision,contract_version,views)
   values(p_project,p_artifact,revision,1,views);
 for d in select * from jsonb_array_elements(recipe->'definitions') loop
   insert into bob.artifact_assembly_definitions(project_id,artifact_id,artifact_revision,definition_key,part_id,part_revision,shape)
    values(p_project,p_artifact,revision,d->>'key',(d->>'part_id')::uuid,(d->>'part_revision')::integer,d->'shape');
 end loop;
 for i in select * from jsonb_array_elements(recipe->'instances') loop
   insert into bob.artifact_assembly_instances(project_id,artifact_id,artifact_revision,instance_key,definition_key,x_mm,y_mm,z_mm,rx_deg,ry_deg,rz_deg)
    values(p_project,p_artifact,revision,i->>'key',i->>'definition_key',
      (i->'position_mm'->>0)::numeric,(i->'position_mm'->>1)::numeric,(i->'position_mm'->>2)::numeric,
      (i->'rotation_deg'->>0)::numeric,(i->'rotation_deg'->>1)::numeric,(i->'rotation_deg'->>2)::numeric);
 end loop;
 return saved;
end $$;
create function bob.artifact_assembly_command(p_project text,p_action text,p_artifact uuid,p_expected integer,p_data jsonb)
returns jsonb language sql security invoker set search_path='' as $$
 select bob_private.artifact_assembly_command(p_project,p_action,p_artifact,p_expected,p_data)
$$;
revoke all on function bob_private.artifact_assembly_command(text,text,uuid,integer,jsonb),bob.artifact_assembly_command(text,text,uuid,integer,jsonb) from public,anon,authenticated;
grant execute on function bob_private.artifact_assembly_command(text,text,uuid,integer,jsonb),bob.artifact_assembly_command(text,text,uuid,integer,jsonb) to authenticated;

create function bob.search_bob_project_data_v8(p_project_id text,p_dataset text,p_query text default null,p_status text default null,
 p_area_id text default null,p_record_id text default null,p_after_id text default null)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare r jsonb; rows jsonb;
begin
 r:=bob.search_bob_project_data_v7(p_project_id,p_dataset,p_query,p_status,p_area_id,p_record_id,p_after_id);
 if p_dataset<>'artifacts' then return r;end if;
 select coalesce(jsonb_agg(item.value||jsonb_build_object(
   'has_generic_assembly',a.artifact_id is not null,
   'assembly',case when p_record_id is not null then to_jsonb(a) else null end) order by item.ord),'[]'::jsonb) into rows
 from jsonb_array_elements(r->'records') with ordinality item(value,ord)
 left join bob.artifact_assembly_details a on a.project_id=p_project_id and a.artifact_id::text=item.value->>'id'
   and a.artifact_revision=(item.value->>'revision')::integer;
 return jsonb_set(r,'{records}',rows);
end $$;
revoke all on function bob.search_bob_project_data_v8(text,text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function bob.search_bob_project_data_v8(text,text,text,text,text,text,text) to authenticated;

create function bob_private.bob_project_write_v8(p_project text,p_thread uuid,p_turn uuid,p_generation bigint,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare d jsonb; rid uuid; prior jsonb; record jsonb; result jsonb; message text; quote text;
 key text; existing bob_private.bob_write_receipts; expected integer; creating boolean;
begin
 if p_payload->>'kind' is distinct from 'assembly' then return bob_private.bob_project_write_v7(p_project,p_thread,p_turn,p_generation,p_payload);end if;
 perform bob_private.bob_assert_write_claim(p_project,p_thread,p_turn,p_generation);
 if p_payload is null or jsonb_typeof(p_payload)<>'object' or octet_length(p_payload::text)>150000
   or p_payload-array['kind','record_id','expected_updated_at','expected_revision','request_quote','data']::text[]<>'{}'::jsonb
   or (select count(*) from jsonb_object_keys(p_payload))<>6 or p_payload->'expected_updated_at' is distinct from 'null'::jsonb
   or jsonb_typeof(p_payload->'expected_revision')<>'number' or (p_payload->>'expected_revision')!~'^\d+$'
   or jsonb_typeof(p_payload->'request_quote')<>'string' or length(p_payload->>'request_quote') not between 1 and 500
   or jsonb_typeof(p_payload->'data')<>'object' then raise exception 'invalid_write' using errcode='22023';end if;
 quote:=p_payload->>'request_quote';d:=p_payload->'data';
 select text into message from bob.bob_messages where thread_id=p_thread and turn_id=p_turn and role='user';
 if message is null or position(quote in message)=0 then raise exception 'request_quote_required' using errcode='22023';end if;
 creating:=p_payload->'record_id'='null'::jsonb; expected:=(p_payload->>'expected_revision')::integer;
 if (creating and expected<>0) or (not creating and expected<1) then raise exception 'invalid_write' using errcode='22023';end if;
 key:='assembly:'||coalesce(p_payload->>'record_id',concat_ws(':','new',d->>'area_id',lower(btrim(d->>'title'))));
 select * into existing from bob_private.bob_write_receipts
  where project_id=p_project and actor_id=auth.uid() and turn_id=p_turn and operation_key=key;
 if found then
   if existing.payload is distinct from p_payload then raise exception 'operation_reused' using errcode='40001';end if;
   return existing.receipt;
 end if;
 if(select count(*) from bob_private.bob_write_receipts where project_id=p_project and actor_id=auth.uid() and turn_id=p_turn)>=8 then
   raise exception 'write_budget_exhausted' using errcode='22023';end if;
 if creating then rid:=gen_random_uuid();
 else
   rid:=(p_payload->>'record_id')::uuid;
   select to_jsonb(a) into prior from bob.artifact_assembly_details a join bob.artifacts h on h.id=a.artifact_id and h.current_revision=a.artifact_revision
    where a.project_id=p_project and a.artifact_id=rid;
   if not found then raise exception 'project_denied' using errcode='42501';end if;
 end if;
 perform bob_private.artifact_assembly_command(p_project,case when creating then 'create' else 'revise' end,rid,expected,d);
 select jsonb_build_object('id',ar.id,'title',ar.title,'area_id',ar.area_id,'revision',ar.revision,'status',ar.status,
   'target_revision',ar.target_revision,'solution_id',ar.solution_id,'solution_revision',ar.solution_revision,'assembly',to_jsonb(a)) into record
  from bob.current_artifacts ar join bob.artifact_assembly_details a on a.project_id=ar.project_id and a.artifact_id=ar.id and a.artifact_revision=ar.revision
  where ar.project_id=p_project and ar.id=rid;
 if record is null then raise exception 'write_readback_failed';end if;
 result:=jsonb_build_object('projectId',p_project,'dataset','artifacts','recordId',rid,'label',record->>'title',
  'operation',case when creating then 'created' else 'updated' end,'savedAt',clock_timestamp(),
  'revision',(record->>'revision')::integer,'areaId',record->'area_id','record',record);
 insert into bob_private.bob_write_receipts(project_id,actor_id,turn_id,operation_key,payload,before_record,receipt)
  values(p_project,auth.uid(),p_turn,key,p_payload,prior,result);
 return result;
end $$;
create function bob.bob_project_write_v8(p_project text,p_thread uuid,p_turn uuid,p_generation bigint,p_payload jsonb)
returns jsonb language sql security invoker set search_path='' as $$
 select bob_private.bob_project_write_v8(p_project,p_thread,p_turn,p_generation,p_payload)
$$;
revoke all on function bob_private.bob_project_write_v8(text,uuid,uuid,bigint,jsonb),bob.bob_project_write_v8(text,uuid,uuid,bigint,jsonb) from public,anon,authenticated;
grant execute on function bob_private.bob_project_write_v8(text,uuid,uuid,bigint,jsonb),bob.bob_project_write_v8(text,uuid,uuid,bigint,jsonb) to authenticated;

insert into bob.tool_catalog(name,description,how_to,schema_version,always_load,preload_phases,active) values(
 'save_project_assembly',
 'Create or revise a generic versioned part assembly that can be rendered by Bob\'s CAD adapter. Uses catalog parts, reusable generic geometry and placed instances; not an object-specific generator.',
 'Search/read exact catalog part revisions first. Build definitions from supported generic geometry only (box = length/width/thickness, tube = OD/wall/length), then place one or more instances with stable keys. Known catalog dimensions must match; parameter slots may be resolved here, but an unknown critical part dimension cannot be invented. Moving an instance changes placement only. Use mm working dimensions. Preserve target and measurement lineage. CAD validation happens before the database write; a successful save remains Concept, not engineering/manufacturing approval. No stock, Shopping, order or physical Building state is changed.',
 1,false,array['design','planning'],true
);

revoke all on function bob_private.valid_assembly_key(text),bob_private.valid_assembly_number(jsonb,boolean,numeric),
 bob_private.valid_assembly_shape(jsonb),bob_private.valid_assembly_views(text[]),bob_private.valid_assembly_recipe(jsonb),
 bob_private.assembly_property_compatible(jsonb,text,numeric),bob_private.assembly_part_shape_compatible(text,uuid,integer,jsonb),
 bob_private.carry_generic_assembly(),bob_private.check_single_artifact_recipe(),
 bob_private.artifact_assembly_command(text,text,uuid,integer,jsonb),bob.artifact_assembly_command(text,text,uuid,integer,jsonb),
 bob.search_bob_project_data_v8(text,text,text,text,text,text,text),
 bob_private.bob_project_write_v8(text,uuid,uuid,bigint,jsonb),bob.bob_project_write_v8(text,uuid,uuid,bigint,jsonb)
 from public,anon,authenticated;
grant execute on function bob_private.valid_assembly_key(text),bob_private.valid_assembly_number(jsonb,boolean,numeric),
 bob_private.valid_assembly_shape(jsonb),bob_private.valid_assembly_views(text[]),bob_private.valid_assembly_recipe(jsonb),
 bob_private.assembly_property_compatible(jsonb,text,numeric),bob_private.assembly_part_shape_compatible(text,uuid,integer,jsonb),
 bob_private.artifact_assembly_command(text,text,uuid,integer,jsonb),bob.artifact_assembly_command(text,text,uuid,integer,jsonb),
 bob.search_bob_project_data_v8(text,text,text,text,text,text,text),
 bob_private.bob_project_write_v8(text,uuid,uuid,bigint,jsonb),bob.bob_project_write_v8(text,uuid,uuid,bigint,jsonb)
 to authenticated;

notify pgrst,'reload schema';
commit;
