-- Generated by scripts/build-ai-handoff-catalog.ts from executable declarations.
-- Deploy compatible handlers before publishing. Pinned manifests stay immutable.
begin;
do $cad_handoff_values$
declare patch jsonb; current_version record; definition jsonb; metadata jsonb;
  next_version integer; version_id uuid; activation jsonb := '{}';
begin
  perform pg_advisory_xact_lock(hashtextextended('ai_catalog:bob',0));
  for patch in select value from jsonb_array_elements($cad_handoff_contracts$[
  {
    "key": "tools.design_project_cad",
    "description": "Delegate a requested CAD drawing from the current selected Solution and its purpose-specific design intent. Resolve consequential choices through expert advice and supported selections before fixing construction geometry; reuse prior decisions and delegation. An exploratory form sketch may retain explicitly deferred choices within its stated scope. For a construction concept with parts, material revisions and typed joints, use save_construction_draft and check_construction_draft first; this drawing tool cannot replace that deliverable or repair catalog definitions. Selected original images accompany the same pinned intent for designer and reviewer. Intake returns remaining needs together; reuse existing Tasks/Steps or gather measurements in chat, then resume the same request_id. Returns a checked candidate, not a saved drawing. Specify coordinate/view directions and relevant object IDs; the assistant can fetch wider dependencies.",
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "request_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Copy the saved drawing request ID to resume after complements. Null only for a new request. With an ID, pass handoff:null and requirement_changes:[] to reuse ALL saved requirements. When the owner writes again about a request that stopped at its cost or call limit, call this immediately with that ID; the owner's new message renews the budget, which the server adds. Do not re-read requests, budgets or sources first."
        },
        "brief": {
          "type": "string"
        },
        "handoff": {
          "anyOf": [
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "deliverable": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 2000
                },
                "requirements": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 24,
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "requirement": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 2000
                      },
                      "basis": {
                        "type": "string",
                        "enum": [
                          "user_request",
                          "project_record",
                          "working_assumption"
                        ]
                      },
                      "source_ref": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "maxLength": 500
                      }
                    },
                    "required": [
                      "requirement",
                      "basis",
                      "source_ref"
                    ]
                  }
                },
                "coordinates": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "origin": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    },
                    "positive_x": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    },
                    "positive_y": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    },
                    "positive_z": {
                      "type": [
                        "string",
                        "null"
                      ],
                      "maxLength": 500
                    }
                  },
                  "required": [
                    "origin",
                    "positive_x",
                    "positive_y",
                    "positive_z"
                  ]
                },
                "views": {
                  "type": "array",
                  "minItems": 1,
                  "maxItems": 4,
                  "uniqueItems": true,
                  "items": {
                    "type": "string",
                    "enum": [
                      "front",
                      "right",
                      "top",
                      "isometric"
                    ]
                  }
                },
                "unresolved": {
                  "type": "array",
                  "maxItems": 20,
                  "items": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000
                  }
                }
              },
              "required": [
                "deliverable",
                "requirements",
                "coordinates",
                "views",
                "unresolved"
              ]
            },
            {
              "type": "null"
            }
          ],
          "description": "New request only: transfer owner requirements without IDs; the server creates and persists their identities. Map coordinates and views, keep unknown directions null and cite exact source refs. Resume with null: the server reads the saved handoff, including earlier corrections. Use requirement_changes only for explicit additions or changes."
        },
        "requirement_changes": {
          "type": "array",
          "maxItems": 24,
          "description": "Explicit changes to a saved request only. Empty to resume. Copy requirement_id from the saved handoff to update it; null only for a genuinely new requirement. Never invent an ID. Earlier requirements are retained.",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "requirement_id": {
                "type": [
                  "string",
                  "null"
                ],
                "maxLength": 40
              },
              "requirement": {
                "type": "string",
                "minLength": 1,
                "maxLength": 2000
              },
              "basis": {
                "type": "string",
                "enum": [
                  "user_request",
                  "project_record",
                  "working_assumption"
                ]
              },
              "source_ref": {
                "type": [
                  "string",
                  "null"
                ],
                "maxLength": 500
              }
            },
            "required": [
              "requirement_id",
              "requirement",
              "basis",
              "source_ref"
            ]
          }
        },
        "area_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "component_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "step_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Current work Step this drawing supports; read the plan and pass its exact ID when relevant. Null for a project-wide drawing. Planning is a phase."
        },
        "artifact_id": {
          "type": [
            "string",
            "null"
          ],
          "description": "Exact existing construction checkpoint to draw, or CAD Artifact to revise. A construction is freshly checked and rendered verbatim into a separate linked concept drawing; it is never redesigned here. Null only when no existing construction applies."
        }
      },
      "required": [
        "request_id",
        "brief",
        "handoff",
        "requirement_changes",
        "area_id",
        "component_id",
        "step_id",
        "artifact_id"
      ]
    }
  },
  {
    "key": "tools.plan_cad_pieces",
    "description": "Split one large build (a room, extension, house, or anything with more than about 24 parts or several structural systems) into 2-12 pieces that are each designed and saved as their own drawing. Pieces are queued and designed one at a time after this reply; each saved piece appears in this conversation. A failed piece does not stop the others and can be resumed by its request_id with design_project_cad. Give every piece a complete standalone brief and handoff in the same shared coordinate system (state the origin and axes once in assembly_brief and repeat them in each handoff). For a single small object use design_project_cad instead.",
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "assembly_title",
        "assembly_brief",
        "area_id",
        "pieces"
      ],
      "properties": {
        "assembly_title": {
          "type": "string",
          "maxLength": 200
        },
        "assembly_brief": {
          "type": "string",
          "maxLength": 3000,
          "description": "Whole-build intent, shared origin/axes and how the pieces meet."
        },
        "area_id": {
          "type": [
            "string",
            "null"
          ]
        },
        "pieces": {
          "type": "array",
          "minItems": 2,
          "maxItems": 12,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "piece_key",
              "brief",
              "component_id",
              "handoff"
            ],
            "properties": {
              "piece_key": {
                "type": "string",
                "pattern": "^[a-z][a-z0-9_-]{0,39}$",
                "description": "Stable short key, e.g. wall_north, floor, roof, bunk_bed."
              },
              "brief": {
                "type": "string",
                "maxLength": 5000
              },
              "component_id": {
                "type": [
                  "string",
                  "null"
                ]
              },
              "handoff": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "deliverable": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 2000
                  },
                  "requirements": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 24,
                    "items": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "requirement": {
                          "type": "string",
                          "minLength": 1,
                          "maxLength": 2000
                        },
                        "basis": {
                          "type": "string",
                          "enum": [
                            "user_request",
                            "project_record",
                            "working_assumption"
                          ]
                        },
                        "source_ref": {
                          "type": [
                            "string",
                            "null"
                          ],
                          "maxLength": 500
                        }
                      },
                      "required": [
                        "requirement",
                        "basis",
                        "source_ref"
                      ]
                    }
                  },
                  "coordinates": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "origin": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "maxLength": 500
                      },
                      "positive_x": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "maxLength": 500
                      },
                      "positive_y": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "maxLength": 500
                      },
                      "positive_z": {
                        "type": [
                          "string",
                          "null"
                        ],
                        "maxLength": 500
                      }
                    },
                    "required": [
                      "origin",
                      "positive_x",
                      "positive_y",
                      "positive_z"
                    ]
                  },
                  "views": {
                    "type": "array",
                    "minItems": 1,
                    "maxItems": 4,
                    "uniqueItems": true,
                    "items": {
                      "type": "string",
                      "enum": [
                        "front",
                        "right",
                        "top",
                        "isometric"
                      ]
                    }
                  },
                  "unresolved": {
                    "type": "array",
                    "maxItems": 20,
                    "items": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 2000
                    }
                  }
                },
                "required": [
                  "deliverable",
                  "requirements",
                  "coordinates",
                  "views",
                  "unresolved"
                ]
              }
            }
          }
        }
      }
    }
  }
]$cad_handoff_contracts$::jsonb) loop
    select v.* into current_version from shared.ai_prompts p
      join shared.ai_prompt_versions v on v.id=p.active_version_id
      where p.app='bob' and p.prompt_key=patch->>'key' and p.definition_kind='tool_contract';
    if not found then raise exception 'cad_handoff_contract_missing'; end if;
    definition := current_version.definition || jsonb_build_object(
      'description',patch->>'description','parameters',patch->'parameters',
      'required_parameters',patch#>'{parameters,required}',
      'optional_parameters','[]'::jsonb);
    metadata := current_version.metadata || jsonb_build_object('server_owned_values',true,'saved_handoff_resume',true);
    select coalesce(max(version),0)+1 into next_version from shared.ai_prompt_versions where prompt_id=current_version.prompt_id;
    insert into shared.ai_prompt_versions(prompt_id,version,definition_kind,definition_format_version,
      metadata,content,definition,flow,available_variables)
    values(current_version.prompt_id,next_version,current_version.definition_kind,current_version.definition_format_version,
      metadata,current_version.content,definition,current_version.flow,current_version.available_variables)
    returning id into version_id;
    activation := activation || jsonb_build_object(patch->>'key',version_id);
  end loop;
  perform shared.activate_ai_catalog('bob',activation);
end $cad_handoff_values$;
commit;
